/* =============================================================
   Dados do guia The End
   -------------------------------------------------------------
   O passo a passo para derrotar o Dragão de Ender, o kit, o que
   dá para conseguir no End e onde fica cada coisa. Java Edition 26.3:
   os baús das Cidades do End foram calculados das tabelas de loot do
   jogo; o resto foi conferido na Minecraft Wiki.
   ============================================================= */
window.MINEGUIA_END = {
  passos: [
    {"id": "preparar", "titulo": "Prepare o seu kit", "curto": "O que levar", "icone": "diamond_chestplate", "texto": ["No End não tem volta: só dá para sair derrotando o dragão (ou morrendo). Antes de pular no portal, separe tudo isto:"], "dica": "Deixe o que é mais valioso num baú em casa. Se você cair no vazio, tudo o que estava com você some para sempre."},
    {"id": "fortaleza", "titulo": "Ache a Fortaleza", "curto": "Siga o olho", "icone": "ender_eye", "texto": ["Faça Olhos de Ender: 1 Pérola de Ender + 1 Pó de Blaze, na bancada.", "Jogue um olho para o alto: ele voa na direção da fortaleza mais próxima. Ande para esse lado e jogue outro de vez em quando.", "Quando o olho, em vez de seguir em frente, descer para o chão, a fortaleza está embaixo de você. Cave em escada, nunca reto para baixo.", "Às vezes o olho quebra quando cai: leve uns 20."], "link": ["superficie.html#estrutura-fortaleza", "Veja a Fortaleza no guia A Superfície"], "dica": "Pérolas de Ender vêm dos Endermen (ou dos clérigos da vila); Pó de Blaze vem das Varas de Blaze do Nether."},
    {"id": "portal", "titulo": "Ative o portal", "curto": "12 olhos", "icone": "end_portal_frame", "texto": ["Na fortaleza, procure a sala do portal: tem uma escada, lava embaixo e um gerador de Traças. Quebre o gerador antes de tudo.", "O portal tem 12 molduras. Coloque um Olho de Ender em cada moldura vazia (algumas já vêm com olho).", "Com as 12 completas, o portal acende. Pule dentro.", "Você chega na ilha principal ou numa plataforma de obsidiana perto dela. Se for a plataforma, faça uma ponte com blocos."], "dica": "Antes de pular, coloque uma cama perto do portal e durma nela: se você morrer no End, volta para cá."},
    {"id": "cristais", "titulo": "Destrua os cristais", "curto": "Os 10 cristais", "icone": "end_crystal", "img": "cristais.jpg", "texto": ["Em volta da ilha há 10 torres de obsidiana com um Cristal do End no topo. Enquanto existir um cristal, ele cura o dragão.", "Acerte cada cristal com uma flecha ou uma bola de neve, de longe. Mire um pouquinho acima dele.", "Dois cristais ficam dentro de gaiolas de ferro. Suba a torre com blocos (ou com uma pérola), quebre as grades com a picareta, afaste-se e acerte o cristal.", "A explosão do cristal é forte: nunca bata nele com a espada. E se ele explodir enquanto cura o dragão, o dragão leva 10 de dano."], "dica": "Coloque a Abóbora Esculpida na cabeça: assim você pode olhar para os Endermen à vontade, sem deixá-los bravos."},
    {"id": "dragao", "titulo": "Derrote o dragão", "curto": "100 corações", "icone": "dragon_head", "img": "dragao.jpg", "texto": ["O Dragão de Ender tem 200 de vida (100 corações). Só a cabeça leva o dano inteiro: no resto do corpo, cada golpe vale só 1/4.", "Enquanto ele voa, atire flechas na cabeça.", "De vez em quando ele pousa no portal do meio da ilha. Pousado, ele é imune a flechas: corra até lá e bata na cabeça com a espada.", "Cuidado com o bafo roxo e com as bolas de fogo: as nuvens roxas machucam. Saia de dentro delas (e aproveite para encher frascos com Bafo do Dragão)."], "facil": ["Destrua todos os cristais primeiro.", "Fique perto do portal do meio (o buraco de pedra-base) e espere o dragão pousar.", "Beba uma Poção de Força e bata na cabeça com a espada até ele levantar voo.", "Enquanto ele voa, atire na cabeça com o arco e espere o próximo pouso.", "Repita até ele cair. Coma uma maçã dourada sempre que a vida baixar."], "avancado": "Camas explodem no End. Com o dragão pousado, fique dentro do buraco do portal, coloque uma cama perto da cabeça dele e um bloco do seu lado, e clique na cama. Cada explosão tira até 1/4 da vida dele. É rápido, mas perigoso: use armadura com Proteção contra Explosões.", "dica": "A vida do dragão aparece na barra roxa no alto da tela. Se ela subir, ainda tem cristal de pé."},
    {"id": "depois", "titulo": "Depois da vitória", "curto": "A recompensa", "icone": "dragon_egg", "texto": ["O dragão solta 12.000 de experiência: dá para ir do nível 0 ao 68 de uma vez.", "O portal do meio se acende. Pule nele para voltar para casa (e ver os créditos do jogo).", "O Ovo do Dragão aparece em cima do portal. Ele se teletransporta quando você bate: empurre com um pistão para ele cair como item.", "Aparece também uma Passagem do End na beirada da ilha. Jogue uma Pérola de Ender dentro dela para chegar às ilhas externas, onde estão as Cidades do End e os Élitros.", "Quer lutar de novo? 4 Cristais do End nas bordas do portal trazem o dragão de volta (dessa vez sem ovo, e com 500 de experiência)."], "dica": "Antes de voltar para casa, aproveite a Passagem do End: é o único jeito fácil de conseguir os Élitros."}
  ],
  kit: [
    ["diamond_chestplate", "Armadura de diamante ou netherita", "Com Proteção IV. No Difícil, o dragão tira até 7,5 corações com a cabeça.", true],
    ["diamond_boots", "Botas com Peso-Pena IV", "A queda é o que mais derruba gente no End.", true],
    ["diamond_sword", "Espada com Afiação", "Para bater no dragão quando ele pousa.", true],
    ["bow", "Arco com Força e Infinidade", "Para os cristais e para o dragão em voo. Sem Infinidade, leve 2 ou 3 pilhas de flechas.", true],
    ["snowball", "Bolas de neve", "Estouram os cristais tão bem quanto flechas.", false],
    ["cobblestone", "Algumas pilhas de blocos", "Para subir nas torres e fazer pontes.", true],
    ["diamond_pickaxe", "Picareta", "Você pode chegar embaixo da terra, e precisa quebrar as gaiolas.", true],
    ["golden_apple", "Maçãs douradas e comida", "Curam rápido no meio da luta.", true],
    ["water_bucket", "Balde de água", "Espanta Endermen e salva de quedas.", true],
    ["carved_pumpkin", "Abóbora Esculpida", "Na cabeça, ela deixa você olhar para os Endermen sem irritá-los.", true],
    ["ender_pearl", "Pérolas de Ender", "Levam você ao alto das torres ou de volta para a ilha.", false],
    ["potion:queda-lenta", "Poções de Queda Lenta", "Para descer das torres sem dano.", false],
    ["potion:forca", "Poção de Força", "Deixa cada espadada muito mais forte.", false],
    ["ender_eye", "Uns 20 Olhos de Ender", "Para achar a fortaleza e ativar o portal.", true],
    ["totem_of_undying", "Totem da Imortalidade", "Na outra mão, salva você de uma morte (mas não do vazio).", false]
  ],
  itens: [
    {"id": "elitros", "icone": "elytra", "lugar": "navio", "onde": "Numa moldura, na sala do tesouro do Navio do End.", "uso": "Deixam você planar. Com Fogos de Artifício, você voa de verdade. Conserte com Membrana de Espectro na bigorna ou com Remendo.", "nome": "Élitros"},
    {"id": "cabeca", "icone": "dragon_head", "lugar": "navio", "onde": "Na proa do Navio do End.", "uso": "Decoração rara: dá para usar na cabeça, e ligada na redstone ela abre e fecha a boca.", "nome": "Cabeça do Dragão"},
    {"id": "ovo", "icone": "dragon_egg", "lugar": "ilha", "onde": "Em cima do portal de saída, depois de derrotar o dragão pela primeira vez.", "uso": "Um troféu: só existe um por mundo. Ele teletransporta quando você bate nele, então empurre com um pistão.", "nome": "Ovo do Dragão"},
    {"id": "bafo", "icone": "dragon_breath", "lugar": "ilha", "onde": "Nas nuvens roxas do ataque do dragão: use um Frasco de Vidro dentro delas.", "uso": "Transforma poções arremessáveis em prolongadas, que deixam uma nuvem com o efeito.", "link": ["pocoes.html#como-fazer", "Veja no guia das Poções"], "nome": "Bafo do Dragão"},
    {"id": "casco", "icone": "shulker_shell", "lugar": "cidade", "onde": "Dos Shulkers das Cidades do End: metade das vezes (Pilhagem aumenta a chance).", "uso": "2 cascos + 1 baú = Caixa de Shulker, que guarda os itens mesmo depois de quebrada.", "receita": [["shulker_shell", null, null, "chest", null, null, "shulker_shell", null, null], "shulker_box"], "nome": "Casco de Shulker"},
    {"id": "coro", "icone": "chorus_fruit", "lugar": "externas", "onde": "Das plantas-do-coro das ilhas externas.", "uso": "Comer teletransporta você para perto. Na fornalha vira Fruta-do-Coro Cozida, que faz Purpur e Varas do End.", "nome": "Fruta-do-Coro"},
    {"id": "perola", "icone": "ender_pearl", "lugar": "externas", "onde": "Dos Endermen, que aparecem em todo o End.", "uso": "Jogue para se teletransportar. Com Pó de Blaze, vira Olho de Ender.", "nome": "Pérola de Ender"},
    {"id": "cristal", "icone": "end_crystal", "lugar": "ilha", "onde": "Não aparece pronto: você faz na bancada.", "uso": "4 cristais nas bordas do portal de saída trazem o dragão de volta.", "receita": [["glass", "glass", "glass", "glass", "ender_eye", "glass", "glass", "ghast_tear", "glass"], "end_crystal"], "nome": "Cristal do End"},
    {"id": "purpur", "icone": "purpur_block", "lugar": "cidade", "onde": "As Cidades do End são feitas dele: é só minerar. Ou faça com 4 Frutas-do-Coro Cozidas.", "uso": "Um bloco de construção roxo. Com Vara de Blaze, a fruta cozida também faz Varas do End, que iluminam.", "receita": [["popped_chorus_fruit", "popped_chorus_fruit", null, "popped_chorus_fruit", "popped_chorus_fruit", null, null, null, null], "purpur_block", 4], "nome": "Bloco de Purpur"},
    {"id": "saque", "icone": "chest", "lugar": "cidade", "nome": "Baús do tesouro", "onde": "Nos baús das salas do tesouro das Cidades e dos Navios do End.", "uso": "Ferramentas e armaduras de diamante encantadas, diamantes, ouro e o molde de Enfeite de Espiral, que só existe aqui."},
    {"id": "experiencia", "icone": "experience_bottle", "lugar": "ilha", "nome": "12.000 de experiência", "onde": "Ao derrotar o dragão pela primeira vez.", "uso": "Do nível 0 ao 68 de uma vez: perfeito para encantar tudo na mesa de encantamentos.", "link": ["encantamentos.html", "Veja o guia Os Encantamentos"]}
  ],
  lugares: [
    {"id": "ilha", "nome": "Ilha principal", "icone": "obsidian", "img": "ilha.jpg", "apelido": "A casa do dragão", "descricao": "Uma ilha de pedra do End flutuando no vazio, com 10 torres de obsidiana em círculo e, no meio, o portal de saída, apagado até o dragão morrer.", "onde": "É onde você chega pelo portal da Fortaleza.", "mobs": ["ender_dragon", "enderman"], "destaques": [["end_crystal", "10 torres de obsidiana, cada uma com um Cristal do End no topo"], ["bedrock", "O portal de saída no meio da ilha, que acende quando o dragão morre"], ["dragon_egg", "O Ovo do Dragão aparece aqui depois da luta"]], "dica": "Não pule da beirada: embaixo é o vazio, e quem cai lá perde tudo.", "baus": []},
    {"id": "passagens", "nome": "Passagens do End", "icone": "end_gateway", "img": "passagem.jpg", "apelido": "O atalho para longe", "descricao": "Pequenos portais de pedra-base com uma luz roxa no meio. Cada vez que o dragão morre, nasce uma na beirada da ilha principal (até 20).", "onde": "Flutuando a 96 blocos do centro da ilha principal. Nas ilhas externas também tem uma, que traz você de volta.", "mobs": [], "destaques": [["ender_pearl", "Jogue uma Pérola de Ender dentro da luz para ser levado"], ["bedrock", "Feitas de pedra-base: não dá para quebrar"]], "dica": "Do outro lado você pode cair numa ilha pequena: leve blocos para chegar às ilhas grandes.", "baus": []},
    {"id": "externas", "nome": "Ilhas externas", "icone": "chorus_flower", "img": "externas.jpg", "apelido": "O End de verdade", "descricao": "A mais de 1.000 blocos do centro começam as ilhas externas: muitas ilhas de pedra do End, com florestas de plantas-do-coro e muitos Endermen.", "onde": "Pela Passagem do End, depois de derrotar o dragão.", "biomas": ["Terras altas do End", "Interior do End", "Zona estéril do End", "Ilhas pequenas do End"], "mobs": ["enderman", "endermite"], "destaques": [["chorus_plant", "Florestas de plantas-do-coro"], ["ender_pearl", "Muitos Endermen: ótimo lugar para juntar pérolas"]], "dica": "Os Endermites às vezes aparecem quando você joga uma Pérola de Ender.", "baus": []},
    {"id": "cidade", "nome": "Cidade do End", "icone": "purpur_block", "img": "cidade.jpg", "apelido": "As torres de purpur", "descricao": "Torres altas de purpur e tijolos de pedra do End, iluminadas por Varas do End e guardadas por Shulkers. As salas do tesouro têm baús valiosos.", "onde": "Nas ilhas externas maiores (Terras altas e Interior do End).", "mobs": ["shulker"], "destaques": [["shulker_shell", "Shulkers grudados nas paredes: os tiros deles fazem você flutuar"], ["end_rod", "Varas do End iluminando tudo"], ["ender_chest", "Algumas salas do tesouro têm um Baú de Ender"]], "baus": [{"nome": "Baú do tesouro", "descricao": "Nas salas do tesouro (2 baús por sala).", "por": "bau", "itens": [["gold_ingot", 2, 7, 50.6], ["iron_ingot", 4, 8, 37.0], ["diamond", 2, 7, 20.4], ["beetroot_seeds", 1, 10, 20.4], ["diamond_boots", 1, 1, 12.7, 1], ["iron_boots", 1, 1, 12.7, 1], ["diamond_leggings", 1, 1, 12.7, 1], ["iron_leggings", 1, 1, 12.7, 1], ["diamond_helmet", 1, 1, 12.7, 1], ["iron_helmet", 1, 1, 12.7, 1], ["diamond_sword", 1, 1, 12.7, 1], ["iron_sword", 1, 1, 12.7, 1], ["diamond_spear", 1, 1, 12.7, 1], ["diamond_chestplate", 1, 1, 12.7, 1], ["iron_chestplate", 1, 1, 12.7, 1], ["diamond_pickaxe", 1, 1, 12.7, 1], ["iron_pickaxe", 1, 1, 12.7, 1], ["diamond_shovel", 1, 1, 12.7, 1], ["iron_shovel", 1, 1, 12.7, 1], ["saddle", 1, 1, 12.7], ["emerald", 2, 6, 8.6], ["spire_armor_trim_smithing_template", 1, 1, 6.7], ["copper_horse_armor", 1, 1, 4.4], ["diamond_horse_armor", 1, 1, 4.4], ["iron_horse_armor", 1, 1, 4.4], ["golden_horse_armor", 1, 1, 4.4]]}], "dica": "Leve leite: ele tira a Levitação dos tiros dos Shulkers antes que você caia de muito alto."},
    {"id": "navio", "nome": "Navio do End", "icone": "elytra", "img": "navio.jpg", "apelido": "Onde ficam os Élitros", "descricao": "Um navio flutuando ao lado de algumas Cidades do End (nem toda cidade tem). Guarda os Élitros, a Cabeça do Dragão e 2 baús do tesouro.", "onde": "Ao lado de uma Cidade do End, preso a uma das pontes.", "mobs": ["shulker"], "destaques": [["elytra", "Os Élitros, numa moldura na sala do tesouro"], ["dragon_head", "A Cabeça do Dragão, na proa"], ["potion:cura", "Um suporte de poções com 2 Poções de Cura II"]], "baus": [{"nome": "Baú do tesouro", "descricao": "Nas salas do tesouro (2 baús por sala).", "por": "bau", "itens": [["gold_ingot", 2, 7, 50.6], ["iron_ingot", 4, 8, 37.0], ["diamond", 2, 7, 20.4], ["beetroot_seeds", 1, 10, 20.4], ["diamond_boots", 1, 1, 12.7, 1], ["iron_boots", 1, 1, 12.7, 1], ["diamond_leggings", 1, 1, 12.7, 1], ["iron_leggings", 1, 1, 12.7, 1], ["diamond_helmet", 1, 1, 12.7, 1], ["iron_helmet", 1, 1, 12.7, 1], ["diamond_sword", 1, 1, 12.7, 1], ["iron_sword", 1, 1, 12.7, 1], ["diamond_spear", 1, 1, 12.7, 1], ["diamond_chestplate", 1, 1, 12.7, 1], ["iron_chestplate", 1, 1, 12.7, 1], ["diamond_pickaxe", 1, 1, 12.7, 1], ["iron_pickaxe", 1, 1, 12.7, 1], ["diamond_shovel", 1, 1, 12.7, 1], ["iron_shovel", 1, 1, 12.7, 1], ["saddle", 1, 1, 12.7], ["emerald", 2, 6, 8.6], ["spire_armor_trim_smithing_template", 1, 1, 6.7], ["copper_horse_armor", 1, 1, 4.4], ["diamond_horse_armor", 1, 1, 4.4], ["iron_horse_armor", 1, 1, 4.4], ["golden_horse_armor", 1, 1, 4.4]]}], "dica": "Um Shulker guarda a sala dos Élitros. Pegue-os da moldura com cuidado para não cair."}
  ],
  mobs: {"ender_dragon": {"nome": "Dragão de Ender", "tipo": "hostil", "desc": "O chefão do jogo"}, "enderman": {"nome": "Enderman", "tipo": "neutro", "desc": "Fica bravo se você olhar nos olhos dele"}, "shulker": {"nome": "Shulker", "tipo": "hostil", "desc": "Atira projéteis que fazem você flutuar"}, "endermite": {"nome": "Endermite", "tipo": "hostil", "desc": "Às vezes nasce de uma Pérola de Ender"}},
  icones: {
    "bedrock": ["Rocha Matriz", "bedrock.png"],
    "beetroot_seeds": ["Sementes de Beterraba", "beetroot_seeds.png"],
    "blaze_powder": ["Pó de Blaze", "blaze_powder.png"],
    "bow": ["Arco", "bow.png"],
    "carved_pumpkin": ["Abóbora Esculpida", "carved_pumpkin.png"],
    "chest": ["Baú", "chest.png"],
    "chorus_flower": ["Flor-do-Coro", "chorus_flower.png"],
    "chorus_fruit": ["Fruta-do-Coro", "chorus_fruit.png"],
    "chorus_plant": ["Planta-do-Coro", "chorus_plant.png"],
    "cobblestone": ["Pedregulho", "cobblestone.png"],
    "copper_horse_armor": ["Armadura de Cobre para Cavalo", "copper_horse_armor.png"],
    "diamond": ["Diamante", "diamond.png"],
    "diamond_boots": ["Botas de Diamante", "diamond_boots.png"],
    "diamond_chestplate": ["Peitoral de Diamante", "diamond_chestplate.png"],
    "diamond_helmet": ["Capacete de Diamante", "diamond_helmet.png"],
    "diamond_horse_armor": ["Armadura de Diamante para Cavalo", "diamond_horse_armor.png"],
    "diamond_leggings": ["Calças de Diamante", "diamond_leggings.png"],
    "diamond_pickaxe": ["Picareta de Diamante", "diamond_pickaxe.png"],
    "diamond_shovel": ["Pá de Diamante", "diamond_shovel.png"],
    "diamond_spear": ["Lança de Diamante", "diamond_spear.png"],
    "diamond_sword": ["Espada de Diamante", "diamond_sword.png"],
    "dragon_breath": ["Bafo do Dragão", "dragon_breath.png"],
    "dragon_egg": ["Ovo do Dragão", "dragon_egg.png"],
    "dragon_head": ["Cabeça do Dragão", "dragon_head.png"],
    "elytra": ["Élitros", "elytra.png"],
    "emerald": ["Esmeralda", "emerald.png"],
    "end_crystal": ["Cristal do End", "end_crystal.png"],
    "end_gateway": ["Passagem do End", "end_gateway.png"],
    "end_portal_frame": ["Moldura do Portal do End", "end_portal_frame.png"],
    "end_rod": ["Vara do End", "end_rod.png"],
    "end_stone": ["Pedra do End", "end_stone.png"],
    "ender_chest": ["Baú de Ender", "ender_chest.png"],
    "ender_eye": ["Olho de Ender", "ender_eye.png"],
    "ender_pearl": ["Pérola de Ender", "ender_pearl.png"],
    "experience_bottle": ["Frasco d'Encantamento", "experience_bottle.png"],
    "ghast_tear": ["Lágrima de Ghast", "ghast_tear.png"],
    "glass": ["Vidro", "glass.png"],
    "glass_bottle": ["Frasco de Vidro", "glass_bottle.png"],
    "gold_ingot": ["Lingote de Ouro", "gold_ingot.png"],
    "golden_apple": ["Maçã Dourada", "golden_apple.png"],
    "golden_horse_armor": ["Armadura de Ouro para Cavalo", "golden_horse_armor.png"],
    "iron_boots": ["Botas de Ferro", "iron_boots.png"],
    "iron_chestplate": ["Peitoral de Ferro", "iron_chestplate.png"],
    "iron_helmet": ["Capacete de Ferro", "iron_helmet.png"],
    "iron_horse_armor": ["Armadura de Ferro para Cavalo", "iron_horse_armor.png"],
    "iron_ingot": ["Lingote de Ferro", "iron_ingot.png"],
    "iron_leggings": ["Calças de Ferro", "iron_leggings.png"],
    "iron_pickaxe": ["Picareta de Ferro", "iron_pickaxe.png"],
    "iron_shovel": ["Pá de Ferro", "iron_shovel.png"],
    "iron_sword": ["Espada de Ferro", "iron_sword.png"],
    "obsidian": ["Obsidiana", "obsidian.png"],
    "piston": ["Pistão", "piston.png"],
    "popped_chorus_fruit": ["Fruta-do-Coro Cozida", "popped_chorus_fruit.png"],
    "potion:cura": ["Poção de Cura II", "potion_healing.png"],
    "potion:forca": ["Poção de Força", "potion_strength.png"],
    "potion:queda-lenta": ["Poção de Queda Lenta", "potion_slow_falling.png"],
    "purpur_block": ["Bloco de Purpur", "purpur_block.png"],
    "red_bed": ["Cama Vermelha", "red_bed.png"],
    "saddle": ["Sela", "saddle.png"],
    "shulker_box": ["Caixa de Shulker", "shulker_box.png"],
    "shulker_shell": ["Casco de Shulker", "shulker_shell.png"],
    "snowball": ["Bola de Neve", "snowball.png"],
    "spire_armor_trim_smithing_template": ["Molde de Ferraria (Enfeite de Espiral)", "spire_armor_trim_smithing_template.png"],
    "totem_of_undying": ["Totem da Imortalidade", "totem_of_undying.png"],
    "water_bucket": ["Balde de Água", "water_bucket.png"]
  }
};
