/* =============================================================
   Dados das trocas com os aldeões
   -------------------------------------------------------------
   Trocas da Java Edition (versão 26.3), tiradas da Minecraft Wiki
   (https://minecraft.wiki/w/Trading) e com os nomes oficiais do jogo
   em português.

   Em cada troca:
     nivel      = 1 Novato ... 5 Mestre (no mercador: compra, especial, comum)
     voceDa     = o que você entrega ao aldeão  [quantidade, item]
     voceRecebe = o que o aldeão te dá           [quantidade, item]
     estoque    = quantas vezes dá para trocar antes de ele reabastecer
   Os itens ficam na lista "itens" no final: [nome, arquivo da imagem].
   ============================================================= */
window.MINEGUIA_ALDEOES = {
  niveis: [
    {"n": 1, "nome": "Novato", "insignia": "Pedra"},
    {"n": 2, "nome": "Aprendiz", "insignia": "Ferro"},
    {"n": 3, "nome": "Qualificado", "insignia": "Ouro"},
    {"n": 4, "nome": "Especialista", "insignia": "Esmeralda"},
    {"n": 5, "nome": "Mestre", "insignia": "Diamante"}
  ],
  grupos: [
    {"id": "equipamento", "titulo": "Equipamento: o atalho até o topo", "descricao": "Armaduras, ferramentas e armas — várias já vêm encantadas."},
    {"id": "comida", "titulo": "Comida e fazenda", "descricao": "Para transformar a sua plantação e os seus animais em esmeraldas."},
    {"id": "magia", "titulo": "Livros, magia e mapas", "descricao": "Encantamentos, poções e mapas para explorar o mundo."},
    {"id": "construcao", "titulo": "Construção e decoração", "descricao": "Blocos bonitos e cores para as suas construções."},
    {"id": "visitante", "titulo": "O visitante", "descricao": "Ele não mora na vila, mas sempre aparece com novidades."}
  ],
  profissoes: [
    {
      id: "armeiro-armaduras",
      papel: "Armaduras",
      grupo: "equipamento",
      nome: "Armeiro de Armaduras",
      nomeJogo: "Armeiro",
      estacao: {"id": "blast_furnace", "nome": "Alto-Forno", "receita": ["III", "IFI", "PPP"], "ingredientes": {"I": "iron_ingot", "F": "furnace", "P": "smooth_stone"}},
      apelido: "O alfaiate de metal",
      descricao: "Faz e vende armaduras: de ferro logo no começo, cota de malha no meio do caminho e armadura de diamante encantada nos níveis mais altos. Também compra carvão, ferro, balde de lava e diamante.",
      dica: "Cota de malha não pode ser fabricada na bancada. Comprar do armeiro é o jeito mais fácil de conseguir uma.",
      destaque: {"item": "diamond_chestplate", "texto": "Peitoral de Diamante encantado no nível Mestre: proteção de diamante sem minerar um bloco sequer."},
      trocas: [
        {"nivel": 1, "voceDa": [["15", "coal"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "iron_helmet"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["9", "emerald"]], "voceRecebe": [["1", "iron_chestplate"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["7", "emerald"]], "voceRecebe": [["1", "iron_leggings"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["4", "emerald"]], "voceRecebe": [["1", "iron_boots"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["4", "iron_ingot"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["36", "emerald"]], "voceRecebe": [["1", "bell"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "chainmail_leggings"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "chainmail_boots"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["1", "lava_bucket"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["1", "diamond"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "chainmail_helmet"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["4", "emerald"]], "voceRecebe": [["1", "chainmail_chestplate"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "shield"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["19–33", "emerald"]], "voceRecebe": [["1", "diamond_leggings"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 4, "voceDa": [["13–27", "emerald"]], "voceRecebe": [["1", "diamond_boots"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 5, "voceDa": [["13–27", "emerald"]], "voceRecebe": [["1", "diamond_helmet"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 5, "voceDa": [["21–35", "emerald"]], "voceRecebe": [["1", "diamond_chestplate"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."}
      ]
    },
    {
      id: "ferramenteiro",
      papel: "Ferramentas",
      grupo: "equipamento",
      nome: "Ferramenteiro",
      estacao: {"id": "smithing_table", "nome": "Bancada de Ferraria", "receita": ["II.", "TT.", "TT."], "ingredientes": {"I": "iron_ingot", "T": "oak_planks"}, "obs": "qualquer madeira"},
      apelido: "O dono da caixa de ferramentas",
      descricao: "Vende ferramentas: de pedra no começo e de ferro e de diamante (quase sempre encantadas) depois. Compra carvão, ferro, sílex e diamante.",
      dica: "No nível Qualificado ele pode vender uma Enxada de Diamante por só 4 esmeraldas.",
      destaque: {"item": "diamond_pickaxe", "texto": "Picareta de Diamante encantada no nível Mestre."},
      trocas: [
        {"nivel": 1, "voceDa": [["15", "coal"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "stone_axe"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "stone_shovel"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "stone_pickaxe"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "stone_hoe"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["4", "iron_ingot"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["36", "emerald"]], "voceRecebe": [["1", "bell"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["30", "flint"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["6–20", "emerald"]], "voceRecebe": [["1", "iron_axe"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 3, "voceDa": [["7–21", "emerald"]], "voceRecebe": [["1", "iron_shovel"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 3, "voceDa": [["8–22", "emerald"]], "voceRecebe": [["1", "iron_pickaxe"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 3, "voceDa": [["4", "emerald"]], "voceRecebe": [["1", "diamond_hoe"]], "estoque": 3},
        {"nivel": 4, "voceDa": [["1", "diamond"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["17–31", "emerald"]], "voceRecebe": [["1", "diamond_axe"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 4, "voceDa": [["10–24", "emerald"]], "voceRecebe": [["1", "diamond_shovel"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 5, "voceDa": [["18–32", "emerald"]], "voceRecebe": [["1", "diamond_pickaxe"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."}
      ]
    },
    {
      id: "armeiro-armas",
      papel: "Espadas e machados",
      grupo: "equipamento",
      nome: "Armeiro de Armas",
      nomeJogo: "Armeiro",
      estacao: {"id": "grindstone", "nome": "Rebolo", "receita": ["GLG", "T.T", "..."], "ingredientes": {"G": "stick", "L": "stone_slab", "T": "oak_planks"}, "obs": "qualquer madeira"},
      apelido: "O forjador de lâminas",
      descricao: "Vende machados e espadas de ferro e de diamante, quase sempre encantados. Compra carvão, ferro, sílex e diamante.",
      dica: "Assim como os outros dois ferreiros, compra 15 carvões por 1 esmeralda: a sobra da mineração vira dinheiro.",
      destaque: {"item": "diamond_sword", "texto": "Espada de Diamante encantada no nível Mestre."},
      trocas: [
        {"nivel": 1, "voceDa": [["15", "coal"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "iron_axe"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["7–21", "emerald"]], "voceRecebe": [["1", "iron_sword"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 2, "voceDa": [["4", "iron_ingot"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["36", "emerald"]], "voceRecebe": [["1", "bell"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["24", "flint"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["1", "diamond"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["17–31", "emerald"]], "voceRecebe": [["1", "diamond_axe"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 5, "voceDa": [["13–27", "emerald"]], "voceRecebe": [["1", "diamond_sword"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."}
      ]
    },
    {
      id: "flecheiro",
      papel: "Arcos e flechas",
      grupo: "equipamento",
      nome: "Flecheiro",
      estacao: {"id": "fletching_table", "nome": "Bancada de Arco e Flecha", "receita": ["SS.", "TT.", "TT."], "ingredientes": {"S": "flint", "T": "oak_planks"}, "obs": "qualquer madeira"},
      apelido: "O mestre do arco",
      descricao: "Tudo para quem atira de longe: compra gravetos, sílex, linha, penas e ganchos de armadilha; vende flechas, arcos, bestas e flechas com efeito.",
      dica: "É o aldeão mais fácil de subir de nível no começo do jogo, porque madeira não falta.",
      destaque: {"item": "stick", "texto": "32 gravetos = 1 esmeralda. Quatro troncos de madeira já pagam uma troca!"},
      trocas: [
        {"nivel": 1, "voceDa": [["32", "stick"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["16", "arrow"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["10", "gravel"], ["1", "emerald"]], "voceRecebe": [["10", "flint"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["26", "flint"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["2", "emerald"]], "voceRecebe": [["1", "bow"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["14", "string"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "crossbow"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["24", "feather"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["7–21", "emerald"]], "voceRecebe": [["1", "bow"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 5, "voceDa": [["8", "tripwire_hook"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["8–22", "emerald"]], "voceRecebe": [["1", "crossbow"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 5, "voceDa": [["2", "emerald"], ["5", "arrow"]], "voceRecebe": [["5", "tipped_arrow"]], "estoque": 12, "nota": "O efeito da flecha é sorteado quando a troca aparece."}
      ]
    },
    {
      id: "coureiro",
      papel: "Couro e selas",
      grupo: "equipamento",
      nome: "Coureiro",
      estacao: {"id": "cauldron", "nome": "Caldeirão", "receita": ["I.I", "I.I", "III"], "ingredientes": {"I": "iron_ingot"}},
      apelido: "O estilista da vila",
      descricao: "Trabalha com couro: compra couro, sílex, pele de coelho e escamas de tartaruga; vende armadura de couro tingida, armadura de couro para cavalo e sela.",
      dica: "A armadura de couro vem tingida com uma cor sorteada. Às vezes sai um visual bem estiloso.",
      destaque: {"item": "saddle", "texto": "Sela por 6 esmeraldas no nível Mestre."},
      trocas: [
        {"nivel": 1, "voceDa": [["6", "leather"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "leather_leggings"]], "estoque": 12, "nota": "Vem tingida com uma cor sorteada."},
        {"nivel": 1, "voceDa": [["7", "emerald"]], "voceRecebe": [["1", "leather_chestplate"]], "estoque": 12, "nota": "Vem tingida com uma cor sorteada."},
        {"nivel": 2, "voceDa": [["26", "flint"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "leather_helmet"]], "estoque": 12, "nota": "Vem tingida com uma cor sorteada."},
        {"nivel": 2, "voceDa": [["4", "emerald"]], "voceRecebe": [["1", "leather_boots"]], "estoque": 12, "nota": "Vem tingida com uma cor sorteada."},
        {"nivel": 3, "voceDa": [["9", "rabbit_hide"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["7", "emerald"]], "voceRecebe": [["1", "leather_chestplate"]], "estoque": 12, "nota": "Vem tingida com uma cor sorteada."},
        {"nivel": 4, "voceDa": [["4", "turtle_scute"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["6", "emerald"]], "voceRecebe": [["1", "leather_horse_armor"]], "estoque": 12, "nota": "Vem tingida com uma cor sorteada."},
        {"nivel": 5, "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "leather_helmet"]], "estoque": 12, "nota": "Vem tingida com uma cor sorteada."},
        {"nivel": 5, "voceDa": [["6", "emerald"]], "voceRecebe": [["1", "saddle"]], "estoque": 12}
      ]
    },
    {
      id: "agricultor",
      papel: "Plantações",
      grupo: "comida",
      nome: "Agricultor",
      estacao: {"id": "composter", "nome": "Composteira", "receita": ["L.L", "L.L", "LLL"], "ingredientes": {"L": "oak_slab"}, "obs": "qualquer laje de madeira"},
      apelido: "A máquina de esmeraldas",
      descricao: "Compra o que você planta (trigo, batata, cenoura, beterraba, abóbora e melancia) e vende pão, tortas, biscoitos, bolo e comida dourada.",
      dica: "Uma plantação de batata ou cenoura paga as primeiras trocas de toda a vila. É o jeito mais fácil de juntar esmeraldas.",
      destaque: {"item": "golden_carrot", "texto": "3 Cenouras Douradas por 3 esmeraldas no nível Mestre: uma das melhores comidas do jogo."},
      trocas: [
        {"nivel": 1, "voceDa": [["20", "wheat"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["26", "potato"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["22", "carrot"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["15", "beetroot"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["6", "bread"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["6", "pumpkin"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "pumpkin_pie"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "apple"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["4", "melon"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["3", "emerald"]], "voceRecebe": [["18", "cookie"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "suspicious_stew"]], "estoque": 12, "nota": "O efeito é sorteado: cegueira, super pulo, visão noturna, veneno, saturação ou fraqueza."},
        {"nivel": 4, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "cake"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["3", "emerald"]], "voceRecebe": [["3", "golden_carrot"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["4", "emerald"]], "voceRecebe": [["3", "glistering_melon_slice"]], "estoque": 12}
      ]
    },
    {
      id: "acougueiro",
      papel: "Carnes",
      grupo: "comida",
      nome: "Açougueiro",
      estacao: {"id": "smoker", "nome": "Defumador", "receita": [".T.", "TFT", ".T."], "ingredientes": {"T": "oak_log", "F": "furnace"}, "obs": "qualquer tronco"},
      apelido: "O churrasqueiro",
      descricao: "Compra carne crua, carvão, blocos de alga seca e bagas doces; vende frango e porco assados e ensopado de coelho.",
      dica: "Nos níveis Especialista e Mestre ele compra blocos de alga seca e bagas doces, duas fazendas fáceis de automatizar.",
      destaque: {"item": "cooked_chicken", "texto": "8 Frangos Assados por 1 esmeralda."},
      trocas: [
        {"nivel": 1, "voceDa": [["14", "chicken"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["4", "rabbit"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["7", "porkchop"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "rabbit_stew"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["15", "coal"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "cooked_chicken"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["5", "cooked_porkchop"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["10", "beef"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["7", "mutton"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["10", "dried_kelp_block"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["10", "sweet_berries"]], "voceRecebe": [["1", "emerald"]], "estoque": 12}
      ]
    },
    {
      id: "pescador",
      papel: "Peixes",
      grupo: "comida",
      nome: "Pescador",
      estacao: {"id": "barrel", "nome": "Barril", "receita": ["TLT", "T.T", "TLT"], "ingredientes": {"T": "oak_planks", "L": "oak_slab"}, "obs": "qualquer madeira"},
      apelido: "O lobo do mar",
      descricao: "Compra peixes, linha, carvão e barcos; vende peixe assado, fogueira, balde com bacalhau e vara de pesca encantada.",
      dica: "O barco que ele pede no nível Mestre muda com o bioma da vila: carvalho, abeto, selva, acácia ou carvalho escuro.",
      destaque: {"item": "fishing_rod", "texto": "Vara de Pesca encantada no nível Qualificado."},
      trocas: [
        {"nivel": 1, "voceDa": [["20", "string"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["10", "coal"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "cod_bucket"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["6", "cod"], ["1", "emerald"]], "voceRecebe": [["6", "cooked_cod"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["15", "cod"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["2", "emerald"]], "voceRecebe": [["1", "campfire"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["6", "salmon"], ["1", "emerald"]], "voceRecebe": [["6", "cooked_salmon"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["13", "salmon"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["8–22", "emerald"]], "voceRecebe": [["1", "fishing_rod"]], "estoque": 3, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": 4, "voceDa": [["6", "tropical_fish"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["4", "pufferfish"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["1", "barco_bioma"]], "voceRecebe": [["1", "emerald"]], "estoque": 12, "nota": "A madeira do barco depende do bioma da vila."}
      ]
    },
    {
      id: "bibliotecario",
      papel: "Livros encantados",
      grupo: "magia",
      nome: "Bibliotecário",
      estacao: {"id": "lectern", "nome": "Atril", "receita": ["LLL", ".E.", ".L."], "ingredientes": {"L": "oak_slab", "E": "bookshelf"}, "obs": "qualquer laje de madeira"},
      apelido: "O mais disputado da vila",
      descricao: "Vende livros encantados (inclusive Remendo), estantes, lampiões, vidro, bússola, relógio e velas. Compra papel, livros, bolsas de tinta e livro e pena.",
      dica: "Antes da primeira troca, quebre e recoloque o atril: o aldeão sorteia as ofertas de novo. Repita até aparecer o livro que você quer!",
      destaque: {"item": "enchanted_book", "texto": "Livro encantado com qualquer encantamento, menos Velocidade das Almas, Passos Furtivos e Rajada de Vento."},
      trocas: [
        {"nivel": 1, "voceDa": [["24", "paper"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["9", "emerald"]], "voceRecebe": [["1", "bookshelf"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["5–64", "emerald"], ["1", "book"]], "voceRecebe": [["1", "enchanted_book"]], "estoque": 12, "nota": "O encantamento é sorteado. O preço vai de 5 a 64 esmeraldas conforme o nível; encantamentos de tesouro, como Remendo, custam o dobro."},
        {"nivel": 2, "voceDa": [["4", "book"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "lantern"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["5–64", "emerald"], ["1", "book"]], "voceRecebe": [["1", "enchanted_book"]], "estoque": 12, "nota": "O encantamento é sorteado. O preço vai de 5 a 64 esmeraldas conforme o nível; encantamentos de tesouro, como Remendo, custam o dobro."},
        {"nivel": 3, "voceDa": [["5", "ink_sac"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "glass"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["5–64", "emerald"], ["1", "book"]], "voceRecebe": [["1", "enchanted_book"]], "estoque": 12, "nota": "O encantamento é sorteado. O preço vai de 5 a 64 esmeraldas conforme o nível; encantamentos de tesouro, como Remendo, custam o dobro."},
        {"nivel": 4, "voceDa": [["1", "writable_book"]], "voceRecebe": [["1", "emerald"]], "estoque": 12, "nota": "Era para pedir 2, mas por um bug da Java Edition ele aceita só 1."},
        {"nivel": 4, "voceDa": [["4", "emerald"]], "voceRecebe": [["1", "compass"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "clock"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["5–64", "emerald"], ["1", "book"]], "voceRecebe": [["1", "enchanted_book"]], "estoque": 12, "nota": "O encantamento é sorteado. O preço vai de 5 a 64 esmeraldas conforme o nível; encantamentos de tesouro, como Remendo, custam o dobro."},
        {"nivel": 5, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "red_candle"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "yellow_candle"]], "estoque": 12}
      ]
    },
    {
      id: "clerigo",
      papel: "Poções e magia",
      grupo: "magia",
      nome: "Clérigo",
      estacao: {"id": "brewing_stand", "nome": "Suporte de Poções", "receita": [".B.", "PPP", "..."], "ingredientes": {"B": "blaze_rod", "P": "cobblestone"}, "obs": "pedregulho, pedra-negra ou ardosiabissal"},
      apelido: "O alquimista",
      descricao: "Compra carne podre, ouro, pé de coelho, escamas de tartaruga, frascos de vidro e fungo do Nether; vende redstone, lápis-lazúli, pedra-luminosa, pérolas de Ender e frascos d'encantamento.",
      dica: "32 carnes podres viram 1 esmeralda. Aquela carne de zumbi que ninguém quer finalmente serve para alguma coisa.",
      destaque: {"item": "experience_bottle", "texto": "Frasco d'Encantamento por 3 esmeraldas: experiência engarrafada."},
      trocas: [
        {"nivel": 1, "voceDa": [["32", "rotten_flesh"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["2", "redstone"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["3", "gold_ingot"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "lapis_lazuli"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["2", "rabbit_foot"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["4", "emerald"]], "voceRecebe": [["1", "glowstone"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["4", "turtle_scute"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["9", "glass_bottle"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "ender_pearl"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["22", "nether_wart"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "experience_bottle"]], "estoque": 12}
      ]
    },
    {
      id: "cartografo",
      papel: "Mapas",
      grupo: "magia",
      nome: "Cartógrafo",
      estacao: {"id": "cartography_table", "nome": "Bancada de Cartografia", "receita": ["PP.", "TT.", "TT."], "ingredientes": {"P": "paper", "T": "oak_planks"}, "obs": "qualquer madeira"},
      apelido: "O explorador",
      descricao: "Vende mapas que levam a vilas, monumentos oceânicos, câmaras de desafio e mansões, além de molduras, estandartes e o padrão de estandarte com o globo. Compra papel, vidraças e bússolas.",
      dica: "O padrão de estandarte com o globo só pode ser conseguido trocando com o cartógrafo.",
      destaque: {"item": "woodland_explorer_map", "texto": "Mapa de Exploração da Floresta no nível Mestre: leva direto a uma mansão."},
      trocas: [
        {"nivel": 1, "voceDa": [["24", "paper"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 1, "voceDa": [["7", "emerald"]], "voceRecebe": [["1", "map"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["11", "glass_pane"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["8", "emerald"], ["1", "compass"]], "voceRecebe": [["1", "village_map"]], "estoque": 12, "nota": "Leva a uma vila de outro bioma, que depende de onde o cartógrafo mora."},
        {"nivel": 3, "voceDa": [["1", "compass"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 3, "voceDa": [["13", "emerald"], ["1", "compass"]], "voceRecebe": [["1", "ocean_explorer_map"]], "estoque": 12, "nota": "Leva ao monumento oceânico mais próximo."},
        {"nivel": 3, "voceDa": [["12", "emerald"], ["1", "compass"]], "voceRecebe": [["1", "trial_explorer_map"]], "estoque": 12, "nota": "Leva às câmaras de desafio mais próximas."},
        {"nivel": 4, "voceDa": [["7", "emerald"]], "voceRecebe": [["1", "item_frame"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "estandarte_bioma"]], "estoque": 12, "nota": "A cor depende do bioma da vila."},
        {"nivel": 5, "voceDa": [["8", "emerald"]], "voceRecebe": [["1", "globe_banner_pattern"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["14", "emerald"], ["1", "compass"]], "voceRecebe": [["1", "woodland_explorer_map"]], "estoque": 12, "nota": "Leva à mansão da floresta mais próxima."}
      ]
    },
    {
      id: "pedreiro",
      papel: "Blocos de pedra",
      grupo: "construcao",
      nome: "Pedreiro",
      estacao: {"id": "stonecutter", "nome": "Cortador de Pedras", "receita": ["...", ".I.", "PPP"], "ingredientes": {"I": "iron_ingot", "P": "stone"}},
      apelido: "O construtor",
      descricao: "Compra argila, pedra, granito, andesito, diorito e quartzo do Nether; vende tijolos, blocos polidos, espeleotema, terracota colorida e blocos de quartzo.",
      dica: "Perfeito para quem constrói: são blocos decorativos que dariam bastante trabalho para fabricar.",
      destaque: {"item": "qualquer_blue_glazed_terracotta", "texto": "Terracota Vitrificada de qualquer cor por 1 esmeralda."},
      trocas: [
        {"nivel": 1, "voceDa": [["10", "clay_ball"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["1", "emerald"]], "voceRecebe": [["10", "brick"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["20", "stone"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "chiseled_stone_bricks"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["16", "granite"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["16", "andesite"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["16", "diorite"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "dripstone_block"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "polished_andesite"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "polished_diorite"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "polished_granite"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["12", "quartz"]], "voceRecebe": [["1", "emerald"]], "estoque": 12},
        {"nivel": 4, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "qualquer_orange_terracotta"]], "estoque": 12, "nota": "Cada cor é uma troca diferente."},
        {"nivel": 4, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "qualquer_blue_glazed_terracotta"]], "estoque": 12, "nota": "Cada cor é uma troca diferente."},
        {"nivel": 5, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "quartz_pillar"]], "estoque": 12},
        {"nivel": 5, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "quartz_block"]], "estoque": 12}
      ]
    },
    {
      id: "pastor",
      papel: "Lã e cores",
      grupo: "construcao",
      nome: "Pastor",
      estacao: {"id": "loom", "nome": "Tear", "receita": ["...", "LL.", "TT."], "ingredientes": {"L": "string", "T": "oak_planks"}, "obs": "qualquer madeira"},
      apelido: "O rei das cores",
      descricao: "Compra lã e corantes; vende tesoura, lã e tapetes coloridos, camas, estandartes e quadros.",
      dica: "Cada cor é uma troca diferente, então um mesmo pastor pode oferecer várias cores de lã ou de cama.",
      destaque: {"item": "painting", "texto": "3 Quadros por 2 esmeraldas no nível Mestre."},
      trocas: [
        {"nivel": 1, "voceDa": [["18", "white_wool"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["18", "brown_wool"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["18", "black_wool"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["18", "gray_wool"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 1, "voceDa": [["2", "emerald"]], "voceRecebe": [["1", "shears"]], "estoque": 12},
        {"nivel": 2, "voceDa": [["12", "white_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["12", "gray_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["12", "black_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["12", "light_blue_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["12", "lime_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "qualquer_white_wool"]], "estoque": 16, "nota": "Cada cor é uma troca diferente."},
        {"nivel": 2, "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "qualquer_white_carpet"]], "estoque": 16, "nota": "Cada cor é uma troca diferente."},
        {"nivel": 3, "voceDa": [["12", "yellow_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["12", "light_gray_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["12", "orange_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["12", "red_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["12", "pink_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 3, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "qualquer_red_bed"]], "estoque": 12, "nota": "Cada cor é uma troca diferente."},
        {"nivel": 4, "voceDa": [["12", "brown_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["12", "purple_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["12", "blue_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["12", "green_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["12", "magenta_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["12", "cyan_dye"]], "voceRecebe": [["1", "emerald"]], "estoque": 16},
        {"nivel": 4, "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "qualquer_white_banner"]], "estoque": 12, "nota": "Cada cor é uma troca diferente."},
        {"nivel": 5, "voceDa": [["2", "emerald"]], "voceRecebe": [["3", "painting"]], "estoque": 12}
      ]
    },
    {
      id: "mercador",
      papel: "Itens raros",
      grupo: "visitante",
      nome: "Mercador Ambulante",
      estacao: null,
      apelido: "O visitante misterioso",
      descricao: "Não mora na vila: aparece de vez em quando perto de você, acompanhado de duas lhamas de mercador, e vai embora depois de uns 40 minutos. Não sobe de nível. Cada visita traz 9 trocas sorteadas: 2 compras, 2 ofertas especiais e 5 ofertas comuns.",
      dica: "Desde a versão 26.1 é ele quem vende a Etiqueta, por 1 esmeralda (antes ela era do bibliotecário).",
      destaque: {"item": "blue_ice", "texto": "Gelo Azul, troncos de todos os tipos, mudas, corais e plantas difíceis de achar."},
      trocas: [
        {"nivel": "compra", "voceDa": [["1", "hay_block"]], "voceRecebe": [["1", "emerald"]], "estoque": 2},
        {"nivel": "compra", "voceDa": [["1", "water_bottle"]], "voceRecebe": [["1", "emerald"]], "estoque": 2},
        {"nivel": "compra", "voceDa": [["4", "baked_potato"]], "voceRecebe": [["1", "emerald"]], "estoque": 2},
        {"nivel": "compra", "voceDa": [["1", "milk_bucket"]], "voceRecebe": [["2", "emerald"]], "estoque": 2},
        {"nivel": "compra", "voceDa": [["1", "water_bucket"]], "voceRecebe": [["2", "emerald"]], "estoque": 2},
        {"nivel": "compra", "voceDa": [["1", "fermented_spider_eye"]], "voceRecebe": [["3", "emerald"]], "estoque": 2},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "packed_ice"]], "estoque": 6},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "gunpowder"]], "estoque": 2},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "acacia_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "birch_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "cherry_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "dark_oak_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "jungle_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "mangrove_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "oak_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "pale_oak_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "spruce_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "poplar_log"]], "estoque": 4},
        {"nivel": "especial", "voceDa": [["3", "emerald"]], "voceRecebe": [["3", "podzol"]], "estoque": 6},
        {"nivel": "especial", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "potion_of_invisibility"]], "estoque": 1, "nota": "Dura 8 minutos."},
        {"nivel": "especial", "voceDa": [["6", "emerald"]], "voceRecebe": [["1", "blue_ice"]], "estoque": 6},
        {"nivel": "especial", "voceDa": [["6–20", "emerald"]], "voceRecebe": [["1", "iron_pickaxe"]], "estoque": 1, "encantado": true, "nota": "Vem com encantamentos sorteados; quanto melhor o encantamento, mais caro."},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "fern"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "sugar_cane"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "pumpkin"]], "estoque": 4},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "dandelion"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "poppy"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "allium"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "azure_bluet"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "red_tulip"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "orange_tulip"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "white_tulip"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "pink_tulip"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "oxeye_daisy"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "cornflower"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "blue_orchid"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "lily_of_the_valley"]], "estoque": 7},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "open_eyeblossom"]], "estoque": 7},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "wheat_seeds"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "beetroot_seeds"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "pumpkin_seeds"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "melon_seeds"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "name_tag"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["2", "sulfur_spike"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "white_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "light_gray_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "gray_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "black_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "brown_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "red_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "orange_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "yellow_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "lime_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "green_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "cyan_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "light_blue_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "blue_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "purple_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "magenta_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "pink_dye"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "vine"]], "estoque": 4},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "pale_hanging_moss"]], "estoque": 4},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "brown_mushroom"]], "estoque": 4},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "red_mushroom"]], "estoque": 4},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["3", "shelf_mushroom"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["5", "lily_pad"]], "estoque": 2},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["2", "small_dripleaf"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["8", "sand"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["4", "red_sand"]], "estoque": 6},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["2", "pointed_dripstone"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["2", "rooted_dirt"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["2", "moss_block"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["2", "pale_moss_block"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "wildflowers"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["1", "emerald"]], "voceRecebe": [["1", "tall_dry_grass"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["2", "emerald"]], "voceRecebe": [["1", "golden_dandelion"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["2", "emerald"]], "voceRecebe": [["1", "sea_pickle"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["2", "emerald"]], "voceRecebe": [["1", "glowstone"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "tropical_fish_bucket"]], "estoque": 4},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "pufferfish_bucket"]], "estoque": 4},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "kelp"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "cactus"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "brain_coral_block"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "bubble_coral_block"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "fire_coral_block"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "horn_coral_block"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "tube_coral_block"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["3", "emerald"]], "voceRecebe": [["1", "firefly_bush"]], "estoque": 12},
        {"nivel": "comum", "voceDa": [["4", "emerald"]], "voceRecebe": [["1", "slime_ball"]], "estoque": 5},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "acacia_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "birch_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "cherry_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "dark_oak_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "jungle_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "mangrove_propagule"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "oak_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "pale_oak_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "spruce_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "poplar_sapling"]], "estoque": 8},
        {"nivel": "comum", "voceDa": [["5", "emerald"]], "voceRecebe": [["1", "nautilus_shell"]], "estoque": 5}
      ]
    }
  ],
  itens: {
    "acacia_log": ["Tronco de Acácia", "acacia_log.png"],
    "acacia_sapling": ["Muda de Acácia", "acacia_sapling.png"],
    "allium": ["Flor-de-Alho", "allium.png"],
    "andesite": ["Andesito", "andesite.png"],
    "apple": ["Maçã", "apple.png"],
    "arrow": ["Flecha", "arrow.png"],
    "azure_bluet": ["Pequena-Azul", "azure_bluet.png"],
    "baked_potato": ["Batata Assada", "baked_potato.png"],
    "barco_bioma": ["Barco", "barco_bioma.png"],
    "barrel": ["Barril", "barrel.png"],
    "beef": ["Bife Cru", "beef.png"],
    "beetroot": ["Beterraba", "beetroot.png"],
    "beetroot_seeds": ["Sementes de Beterraba", "beetroot_seeds.png"],
    "bell": ["Sino", "bell.png"],
    "birch_log": ["Tronco de Bétula", "birch_log.png"],
    "birch_sapling": ["Muda de Bétula", "birch_sapling.png"],
    "black_dye": ["Corante Preto", "black_dye.png"],
    "black_wool": ["Lã Preta", "black_wool.png"],
    "blast_furnace": ["Alto-Forno", "blast_furnace.png"],
    "blaze_rod": ["Vara de Blaze", "blaze_rod.png"],
    "blue_dye": ["Corante Azul", "blue_dye.png"],
    "blue_ice": ["Gelo Azul", "blue_ice.png"],
    "blue_orchid": ["Orquídea-Azul", "blue_orchid.png"],
    "book": ["Livro", "book.png"],
    "bookshelf": ["Estante", "bookshelf.png"],
    "bow": ["Arco", "bow.png"],
    "brain_coral_block": ["Bloco de Coral-de-Cérebro", "brain_coral_block.png"],
    "bread": ["Pão", "bread.png"],
    "brewing_stand": ["Suporte de Poções", "brewing_stand.png"],
    "brick": ["Tijolo", "brick.png"],
    "brown_dye": ["Corante Marrom", "brown_dye.png"],
    "brown_mushroom": ["Cogumelo Marrom", "brown_mushroom.png"],
    "brown_wool": ["Lã Marrom", "brown_wool.png"],
    "bubble_coral_block": ["Bloco de Coral-de-Bolha", "bubble_coral_block.png"],
    "cactus": ["Cacto", "cactus.png"],
    "cake": ["Bolo", "cake.png"],
    "campfire": ["Fogueira", "campfire.png"],
    "carrot": ["Cenoura", "carrot.png"],
    "cartography_table": ["Bancada de Cartografia", "cartography_table.png"],
    "cauldron": ["Caldeirão", "cauldron.png"],
    "chainmail_boots": ["Botas de Cota de Malha", "chainmail_boots.png"],
    "chainmail_chestplate": ["Peitoral de Cota de Malha", "chainmail_chestplate.png"],
    "chainmail_helmet": ["Capacete de Cota de Malha", "chainmail_helmet.png"],
    "chainmail_leggings": ["Calças de Cota de Malha", "chainmail_leggings.png"],
    "cherry_log": ["Tronco de Cerejeira", "cherry_log.png"],
    "cherry_sapling": ["Muda de Cerejeira", "cherry_sapling.png"],
    "chicken": ["Frango Cru", "chicken.png"],
    "chiseled_stone_bricks": ["Tijolos de Pedra Talhados", "chiseled_stone_bricks.png"],
    "clay_ball": ["Bola de Argila", "clay_ball.png"],
    "clock": ["Relógio", "clock.gif"],
    "coal": ["Carvão", "coal.png"],
    "cobblestone": ["Pedregulho", "cobblestone.png"],
    "cod": ["Bacalhau Cru", "cod.png"],
    "cod_bucket": ["Balde com Bacalhau", "cod_bucket.png"],
    "compass": ["Bússola", "compass.gif"],
    "composter": ["Composteira", "composter.png"],
    "cooked_chicken": ["Frango Assado", "cooked_chicken.png"],
    "cooked_cod": ["Bacalhau Assado", "cooked_cod.png"],
    "cooked_porkchop": ["Costeleta de Porco Assada", "cooked_porkchop.png"],
    "cooked_salmon": ["Salmão Assado", "cooked_salmon.png"],
    "cookie": ["Biscoito", "cookie.png"],
    "cornflower": ["Centáurea", "cornflower.png"],
    "crossbow": ["Besta", "crossbow.png"],
    "cyan_dye": ["Corante Ciano", "cyan_dye.png"],
    "dandelion": ["Dente-de-Leão", "dandelion.png"],
    "dark_oak_log": ["Tronco de Carvalho Escuro", "dark_oak_log.png"],
    "dark_oak_sapling": ["Muda de Carvalho Escuro", "dark_oak_sapling.png"],
    "diamond": ["Diamante", "diamond.png"],
    "diamond_axe": ["Machado de Diamante", "diamond_axe.png"],
    "diamond_boots": ["Botas de Diamante", "diamond_boots.png"],
    "diamond_chestplate": ["Peitoral de Diamante", "diamond_chestplate.png"],
    "diamond_helmet": ["Capacete de Diamante", "diamond_helmet.png"],
    "diamond_hoe": ["Enxada de Diamante", "diamond_hoe.png"],
    "diamond_leggings": ["Calças de Diamante", "diamond_leggings.png"],
    "diamond_pickaxe": ["Picareta de Diamante", "diamond_pickaxe.png"],
    "diamond_shovel": ["Pá de Diamante", "diamond_shovel.png"],
    "diamond_sword": ["Espada de Diamante", "diamond_sword.png"],
    "diorite": ["Diorito", "diorite.png"],
    "dried_kelp_block": ["Bloco de Algas Secas", "dried_kelp_block.png"],
    "dripstone_block": ["Bloco de Espeleotema", "dripstone_block.png"],
    "emerald": ["Esmeralda", "emerald.png"],
    "enchanted_book": ["Livro Encantado", "enchanted_book.png"],
    "ender_pearl": ["Pérola de Ender", "ender_pearl.png"],
    "estandarte_bioma": ["Estandarte", "estandarte_bioma.png"],
    "experience_bottle": ["Frasco d'Encantamento", "experience_bottle.png"],
    "feather": ["Pena", "feather.png"],
    "fermented_spider_eye": ["Olho de Aranha Fermentado", "fermented_spider_eye.png"],
    "fern": ["Samambaia", "fern.png"],
    "fire_coral_block": ["Bloco de Coral-de-Fogo", "fire_coral_block.png"],
    "firefly_bush": ["Arbusto-Vaga-Lume", "firefly_bush.png"],
    "fishing_rod": ["Vara de Pesca", "fishing_rod.png"],
    "fletching_table": ["Bancada de Arco e Flecha", "fletching_table.png"],
    "flint": ["Sílex", "flint.png"],
    "furnace": ["Fornalha", "furnace.png"],
    "glass": ["Vidro", "glass.png"],
    "glass_bottle": ["Frasco de Vidro", "glass_bottle.png"],
    "glass_pane": ["Vidraça", "glass_pane.png"],
    "glistering_melon_slice": ["Fatia de Melancia Reluzente", "glistering_melon_slice.png"],
    "globe_banner_pattern": ["Padrão de estandarte (globo)", "globe_banner_pattern.png"],
    "glowstone": ["Pedra-Luminosa", "glowstone.png"],
    "gold_ingot": ["Lingote de Ouro", "gold_ingot.png"],
    "golden_carrot": ["Cenoura Dourada", "golden_carrot.png"],
    "golden_dandelion": ["Dente-de-Leão Dourado", "golden_dandelion.png"],
    "granite": ["Granito", "granite.png"],
    "gravel": ["Cascalho", "gravel.png"],
    "gray_dye": ["Corante Cinza", "gray_dye.png"],
    "gray_wool": ["Lã Cinza", "gray_wool.png"],
    "green_dye": ["Corante Verde", "green_dye.png"],
    "grindstone": ["Rebolo", "grindstone.png"],
    "gunpowder": ["Pólvora", "gunpowder.png"],
    "hay_block": ["Fardo de Feno", "hay_block.png"],
    "horn_coral_block": ["Bloco de Coral-de-Chifre", "horn_coral_block.png"],
    "ink_sac": ["Bolsa de Tinta", "ink_sac.png"],
    "iron_axe": ["Machado de Ferro", "iron_axe.png"],
    "iron_boots": ["Botas de Ferro", "iron_boots.png"],
    "iron_chestplate": ["Peitoral de Ferro", "iron_chestplate.png"],
    "iron_helmet": ["Capacete de Ferro", "iron_helmet.png"],
    "iron_ingot": ["Lingote de Ferro", "iron_ingot.png"],
    "iron_leggings": ["Calças de Ferro", "iron_leggings.png"],
    "iron_pickaxe": ["Picareta de Ferro", "iron_pickaxe.png"],
    "iron_shovel": ["Pá de Ferro", "iron_shovel.png"],
    "iron_sword": ["Espada de Ferro", "iron_sword.png"],
    "item_frame": ["Moldura de Item", "item_frame.png"],
    "jungle_log": ["Tronco da Selva", "jungle_log.png"],
    "jungle_sapling": ["Muda da Selva", "jungle_sapling.png"],
    "kelp": ["Alga", "kelp.png"],
    "lantern": ["Lampião", "lantern.png"],
    "lapis_lazuli": ["Lápis-Lazúli", "lapis_lazuli.png"],
    "lava_bucket": ["Balde de Lava", "lava_bucket.png"],
    "leather": ["Couro", "leather.png"],
    "leather_boots": ["Botas de Couro", "leather_boots.png"],
    "leather_chestplate": ["Túnica de Couro", "leather_chestplate.png"],
    "leather_helmet": ["Capuz de Couro", "leather_helmet.png"],
    "leather_horse_armor": ["Armadura de Couro para Cavalo", "leather_horse_armor.png"],
    "leather_leggings": ["Calças de Couro", "leather_leggings.png"],
    "lectern": ["Atril", "lectern.png"],
    "light_blue_dye": ["Corante Azul-Claro", "light_blue_dye.png"],
    "light_gray_dye": ["Corante Cinza-Claro", "light_gray_dye.png"],
    "lily_of_the_valley": ["Lírio-do-Vale", "lily_of_the_valley.png"],
    "lily_pad": ["Nenúfar", "lily_pad.png"],
    "lime_dye": ["Corante Verde-Limão", "lime_dye.png"],
    "loom": ["Tear", "loom.png"],
    "magenta_dye": ["Corante Magenta", "magenta_dye.png"],
    "mangrove_log": ["Tronco de Mangue", "mangrove_log.png"],
    "mangrove_propagule": ["Propágulo de Mangue", "mangrove_propagule.png"],
    "map": ["Mapa em Branco", "map.png"],
    "melon": ["Melancia", "melon.png"],
    "melon_seeds": ["Sementes de Melancia", "melon_seeds.png"],
    "milk_bucket": ["Balde de Leite", "milk_bucket.png"],
    "moss_block": ["Bloco de Musgo", "moss_block.png"],
    "mutton": ["Carne de Carneiro Crua", "mutton.png"],
    "name_tag": ["Etiqueta", "name_tag.png"],
    "nautilus_shell": ["Concha de Náutilo", "nautilus_shell.png"],
    "nether_wart": ["Fungo do Nether", "nether_wart.png"],
    "oak_log": ["Tronco de Carvalho", "oak_log.png"],
    "oak_planks": ["Tábuas de Carvalho", "oak_planks.png"],
    "oak_sapling": ["Muda de Carvalho", "oak_sapling.png"],
    "oak_slab": ["Laje de Carvalho", "oak_slab.png"],
    "ocean_explorer_map": ["Mapa de Exploração do Oceano", "ocean_explorer_map.png"],
    "open_eyeblossom": ["Olhoquídea Aberta", "open_eyeblossom.png"],
    "orange_dye": ["Corante Laranja", "orange_dye.png"],
    "orange_tulip": ["Tulipa Laranja", "orange_tulip.png"],
    "oxeye_daisy": ["Margarida", "oxeye_daisy.png"],
    "packed_ice": ["Gelo Compactado", "packed_ice.png"],
    "painting": ["Quadro", "painting.png"],
    "pale_hanging_moss": ["Musgo Pálido Suspenso", "pale_hanging_moss.png"],
    "pale_moss_block": ["Bloco de Musgo Pálido", "pale_moss_block.png"],
    "pale_oak_log": ["Tronco de Carvalho Pálido", "pale_oak_log.png"],
    "pale_oak_sapling": ["Muda de Carvalho Pálido", "pale_oak_sapling.png"],
    "paper": ["Papel", "paper.png"],
    "pink_dye": ["Corante Rosa", "pink_dye.png"],
    "pink_tulip": ["Tulipa Rosa", "pink_tulip.png"],
    "podzol": ["Podzol", "podzol.png"],
    "pointed_dripstone": ["Espeleotema Pontiagudo", "pointed_dripstone.png"],
    "polished_andesite": ["Andesito Polido", "polished_andesite.png"],
    "polished_diorite": ["Diorito Polido", "polished_diorite.png"],
    "polished_granite": ["Granito Polido", "polished_granite.png"],
    "poplar_log": ["Tronco de Álamo", "poplar_log.png"],
    "poplar_sapling": ["Muda de Álamo", "poplar_sapling.png"],
    "poppy": ["Papoula", "poppy.png"],
    "porkchop": ["Costeleta de Porco Crua", "porkchop.png"],
    "potato": ["Batata", "potato.png"],
    "potion_of_invisibility": ["Poção de Invisibilidade", "potion_of_invisibility.png"],
    "pufferfish": ["Baiacu", "pufferfish.png"],
    "pufferfish_bucket": ["Balde com Baiacu", "pufferfish_bucket.png"],
    "pumpkin": ["Abóbora", "pumpkin.png"],
    "pumpkin_pie": ["Torta de Abóbora", "pumpkin_pie.png"],
    "pumpkin_seeds": ["Sementes de Abóbora", "pumpkin_seeds.png"],
    "purple_dye": ["Corante Roxo", "purple_dye.png"],
    "qualquer_blue_glazed_terracotta": ["Terracota vitrificada (qualquer cor)", "qualquer_blue_glazed_terracotta.png"],
    "qualquer_orange_terracotta": ["Terracota tingida (qualquer cor)", "qualquer_orange_terracotta.png"],
    "qualquer_red_bed": ["Cama (qualquer cor)", "qualquer_red_bed.png"],
    "qualquer_white_banner": ["Estandarte (qualquer cor)", "qualquer_white_banner.png"],
    "qualquer_white_carpet": ["Tapete (qualquer cor)", "qualquer_white_carpet.png"],
    "qualquer_white_wool": ["Lã (qualquer cor)", "qualquer_white_wool.png"],
    "quartz": ["Quartzo do Nether", "quartz.png"],
    "quartz_block": ["Bloco de Quartzo", "quartz_block.png"],
    "quartz_pillar": ["Pilar de Quartzo", "quartz_pillar.png"],
    "rabbit": ["Coelho Cru", "rabbit.png"],
    "rabbit_foot": ["Pé de Coelho", "rabbit_foot.png"],
    "rabbit_hide": ["Pele de Coelho", "rabbit_hide.png"],
    "rabbit_stew": ["Ensopado de Coelho", "rabbit_stew.png"],
    "red_candle": ["Vela Vermelha", "red_candle.png"],
    "red_dye": ["Corante Vermelho", "red_dye.png"],
    "red_mushroom": ["Cogumelo Vermelho", "red_mushroom.png"],
    "red_sand": ["Areia Vermelha", "red_sand.png"],
    "red_tulip": ["Tulipa Vermelha", "red_tulip.png"],
    "redstone": ["Pó de Redstone", "redstone.png"],
    "rooted_dirt": ["Terra Enraizada", "rooted_dirt.png"],
    "rotten_flesh": ["Carne Podre", "rotten_flesh.png"],
    "saddle": ["Sela", "saddle.png"],
    "salmon": ["Salmão Cru", "salmon.png"],
    "sand": ["Areia", "sand.png"],
    "sea_pickle": ["Pepino-do-Mar", "sea_pickle.png"],
    "shears": ["Tesoura", "shears.png"],
    "shelf_mushroom": ["Políporo", "shelf_mushroom.png"],
    "shield": ["Escudo", "shield.png"],
    "slime_ball": ["Bola de Slime", "slime_ball.png"],
    "small_dripleaf": ["Plantaforma Pequena", "small_dripleaf.png"],
    "smithing_table": ["Bancada de Ferraria", "smithing_table.png"],
    "smoker": ["Defumador", "smoker.png"],
    "smooth_stone": ["Pedra Lisa", "smooth_stone.png"],
    "spruce_log": ["Tronco de Abeto", "spruce_log.png"],
    "spruce_sapling": ["Muda de Abeto", "spruce_sapling.png"],
    "stick": ["Graveto", "stick.png"],
    "stone": ["Pedra", "stone.png"],
    "stone_axe": ["Machado de Pedra", "stone_axe.png"],
    "stone_hoe": ["Enxada de Pedra", "stone_hoe.png"],
    "stone_pickaxe": ["Picareta de Pedra", "stone_pickaxe.png"],
    "stone_shovel": ["Pá de Pedra", "stone_shovel.png"],
    "stone_slab": ["Laje de Pedra", "stone_slab.png"],
    "stonecutter": ["Cortador de Pedras", "stonecutter.png"],
    "string": ["Linha", "string.png"],
    "sugar_cane": ["Cana-de-Açúcar", "sugar_cane.png"],
    "sulfur_spike": ["Espeleotema de Enxofre", "sulfur_spike.png"],
    "suspicious_stew": ["Ensopado Suspeito", "suspicious_stew.png"],
    "sweet_berries": ["Bagas Doces", "sweet_berries.png"],
    "tall_dry_grass": ["Grama Seca Alta", "tall_dry_grass.png"],
    "tipped_arrow": ["Flecha com Efeito", "tipped_arrow.png"],
    "trial_explorer_map": ["Mapa de Exploração do Desafio", "trial_explorer_map.png"],
    "tripwire_hook": ["Gancho de Armadilha", "tripwire_hook.png"],
    "tropical_fish": ["Peixe Tropical", "tropical_fish.png"],
    "tropical_fish_bucket": ["Balde com Peixe Tropical", "tropical_fish_bucket.png"],
    "tube_coral_block": ["Bloco de Coral-de-Tubo", "tube_coral_block.png"],
    "turtle_scute": ["Escama de Tartaruga", "turtle_scute.png"],
    "village_map": ["Mapa de Vila", "village_map.png"],
    "vine": ["Trepadeiras", "vine.png"],
    "water_bottle": ["Frasco de Água", "water_bottle.png"],
    "water_bucket": ["Balde de Água", "water_bucket.png"],
    "wheat": ["Trigo", "wheat.png"],
    "wheat_seeds": ["Sementes de Trigo", "wheat_seeds.png"],
    "white_dye": ["Corante Branco", "white_dye.png"],
    "white_tulip": ["Tulipa Branca", "white_tulip.png"],
    "white_wool": ["Lã Branca", "white_wool.png"],
    "wildflowers": ["Flores-Selvagens", "wildflowers.png"],
    "woodland_explorer_map": ["Mapa de Exploração da Floresta", "woodland_explorer_map.png"],
    "writable_book": ["Livro e Pena", "writable_book.png"],
    "yellow_candle": ["Vela Amarela", "yellow_candle.png"],
    "yellow_dye": ["Corante Amarelo", "yellow_dye.png"]
  }
};
