/* =============================================================
   Dados do guia do Nether
   -------------------------------------------------------------
   Biomas, mobs de cada bioma, estruturas e o que vem nos baús, da
   Java Edition 26.3. Os mobs e a frequência de cada um saíram dos
   arquivos de geração do mundo do jogo; os baús foram calculados das
   tabelas de loot (chance de o item aparecer em um baú).

   baús: [item, quantidade mínima, quantidade máxima, chance em %, encantado?]
   ============================================================= */
window.MINEGUIA_NETHER = {
  mobs: {
    "strider": {"nome": "Marchador", "tipo": "passivo", "descricao": "Anda sobre a lava como se fosse chão. Com uma sela e uma Vara com Fungo Distorcido, vira o seu barco no mar de lava.", "drops": ["string"], "biomas": ["descampado", "vale-almas", "floresta-carmesim", "floresta-distorcida", "deltas-basalto"], "estruturas": []},
    "enderman": {"nome": "Enderman", "tipo": "neutro", "descricao": "Fica bravo se você olhar nos olhos dele. No Nether, aparece mais na Floresta distorcida.", "drops": ["ender_pearl"], "biomas": ["descampado", "vale-almas", "floresta-distorcida"], "estruturas": []},
    "piglin": {"nome": "Piglin", "tipo": "neutro", "descricao": "Ataca quem não estiver usando pelo menos uma peça de armadura de ouro. Jogue um lingote de ouro para ele e ele te dá algo em troca (escambo).", "drops": ["golden_sword", "crossbow"], "biomas": ["descampado", "floresta-carmesim"], "estruturas": ["bastiao"]},
    "zombified_piglin": {"nome": "Piglin-Zumbificado", "tipo": "neutro", "descricao": "Fica na dele, mas se você bater em um, todos os outros por perto vêm atrás de você.", "drops": ["rotten_flesh", "gold_nugget", "gold_ingot"], "biomas": ["descampado", "floresta-carmesim"], "estruturas": ["fortaleza"]},
    "blaze": {"nome": "Blaze", "tipo": "hostil", "descricao": "Voa e atira bolas de fogo. Só aparece nas fortalezas. As varas de blaze são essenciais para poções e para os olhos de Ender.", "drops": ["blaze_rod"], "biomas": [], "estruturas": ["fortaleza"]},
    "magma_cube": {"nome": "Cubo de Magma", "tipo": "hostil", "descricao": "Pula em você e, quando morre, se divide em cubos menores.", "drops": ["magma_cream"], "biomas": ["descampado", "deltas-basalto"], "estruturas": ["fortaleza", "bastiao"]},
    "skeleton": {"nome": "Esqueleto", "tipo": "hostil", "descricao": "Atira flechas de longe. No Nether, só aparece no Vale de areia das almas (e nas fortalezas).", "drops": ["bone", "arrow"], "biomas": ["vale-almas"], "estruturas": ["fortaleza"]},
    "wither_skeleton": {"nome": "Esqueleto Wither", "tipo": "hostil", "descricao": "Só aparece nas fortalezas. O golpe dá o efeito Decomposição. Às vezes solta o crânio usado para invocar o Wither.", "drops": ["coal", "bone", "wither_skeleton_skull"], "biomas": [], "estruturas": ["fortaleza"]},
    "ghast": {"nome": "Ghast", "tipo": "hostil", "descricao": "Voa e cospe bolas de fogo de longe. Dica: acerte a bola de fogo com um golpe ou uma flecha para devolvê-la.", "drops": ["ghast_tear", "gunpowder"], "biomas": ["descampado", "vale-almas", "deltas-basalto"], "estruturas": []},
    "hoglin": {"nome": "Hoglin", "tipo": "hostil", "descricao": "Um porco gigante que investe e joga você para o alto. Tem medo de Fungo Distorcido e é uma ótima fonte de comida.", "drops": ["porkchop", "leather"], "biomas": ["floresta-carmesim"], "estruturas": ["bastiao"]},
    "piglin_brute": {"nome": "Piglin Bárbaro", "tipo": "hostil", "descricao": "O segurança dos bastiões: ataca sempre, mesmo se você estiver de ouro. Bate forte com um machado de ouro e não renasce depois de morto.", "drops": ["golden_axe"], "biomas": [], "estruturas": ["bastiao"]}
  },
  biomas: [
    {"id": "descampado", "icone": "netherrack", "perigo": 3, "apelido": "O Nether clássico", "descricao": "Morros de netherrack, um mar de lava lá embaixo e pedra-luminosa pendurada no teto. É onde a maioria dos portais acaba indo parar.", "clima": "Neblina vermelho-escura, sem partículas no ar.", "blocos": ["netherrack", "nether_quartz_ore", "nether_gold_ore", "glowstone", "magma_block", "gravel", "brown_mushroom", "red_mushroom"], "dica": "Os Piglins-Zumbificados estão por todo lado. Não bata em nenhum, ou o grupo inteiro vem atrás de você.", "nome": "Descampado do Nether", "neblina": "#330808", "mobs": [["zombified_piglin", "muito comum"], ["ghast", "comum"], ["piglin", "pouco comum"], ["magma_cube", "raro"], ["enderman", "raro"], ["strider", "na lava"]], "estruturas": ["fortaleza", "bastiao", "portal"], "img": "descampado.jpg"},
    {"id": "vale-almas", "icone": "soul_sand", "perigo": 4, "apelido": "O cemitério do Nether", "descricao": "Um vale de areia e terra das almas, com pilares de basalto, fósseis gigantes e fogo azul. A neblina azulada e as cinzas no ar deixam tudo meio assustador.", "clima": "Neblina azul-esverdeada, com cinzas caindo.", "blocos": ["soul_sand", "soul_soil", "basalt", "bone_block", "nether_quartz_ore", "nether_gold_ore", "glowstone", "magma_block"], "dica": "A areia das almas deixa você lento (a não ser com Velocidade das Almas nas botas). Muitos Ghasts e Esqueletos: leve escudo.", "nome": "Vale de areia das almas", "neblina": "#1b4745", "mobs": [["ghast", "muito comum"], ["skeleton", "comum"], ["enderman", "raro"], ["strider", "na lava"]], "estruturas": ["fortaleza", "bastiao", "fossil", "portal"], "img": "vale-almas.jpg"},
    {"id": "floresta-carmesim", "icone": "crimson_nylium", "perigo": 3, "apelido": "A floresta vermelha", "descricao": "Fungos gigantes vermelhos no lugar das árvores, chão de nicélio carmesim, trepadeiras-choronas caindo do teto e cogubrilhos iluminando tudo.", "clima": "Neblina vermelha, com esporos carmesim flutuando.", "blocos": ["crimson_nylium", "crimson_stem", "nether_wart_block", "shroomlight", "weeping_vines", "crimson_fungus", "crimson_roots", "netherrack"], "dica": "É o melhor lugar para conseguir comida no Nether, por causa dos Hoglins. Mas eles atacam: vá preparado.", "nome": "Floresta carmesim", "neblina": "#330303", "mobs": [["hoglin", "muito comum"], ["piglin", "comum"], ["zombified_piglin", "pouco comum"], ["strider", "na lava"]], "estruturas": ["fortaleza", "bastiao", "portal"], "img": "floresta-carmesim.jpg"},
    {"id": "floresta-distorcida", "icone": "warped_nylium", "perigo": 1, "apelido": "O lugar mais seguro do Nether", "descricao": "Fungos gigantes azul-esverdeados, chão de nicélio distorcido e trepadeiras-retorcidas crescendo para cima. Quase nenhum monstro aparece aqui.", "clima": "Neblina roxo-escura, com esporos distorcidos flutuando.", "blocos": ["warped_nylium", "warped_stem", "warped_wart_block", "shroomlight", "twisting_vines", "warped_fungus", "warped_roots", "nether_sprouts"], "dica": "Ótimo lugar para montar uma base no Nether. Os Endermen daqui também rendem muitas pérolas de Ender.", "nome": "Floresta distorcida", "neblina": "#1a051a", "mobs": [["enderman", "o único monstro"], ["strider", "na lava"]], "estruturas": ["fortaleza", "bastiao", "portal"], "img": "floresta-distorcida.jpg"},
    {"id": "deltas-basalto", "icone": "basalt", "perigo": 5, "apelido": "O terreno mais difícil", "descricao": "Colunas de basalto, pedra-negra, poças de lava por toda parte e um chão todo irregular. As cinzas brancas no ar quase não deixam ver nada.", "clima": "Neblina cinza, com muita cinza branca caindo.", "blocos": ["basalt", "blackstone", "magma_block", "nether_quartz_ore", "nether_gold_ore", "glowstone", "netherrack"], "dica": "Cheio de Cubos de Magma: ótimo para juntar creme de magma (para poções de resistência ao fogo). Ande devagar, a lava está em todo lugar.", "nome": "Deltas de basalto", "neblina": "#685f70", "mobs": [["magma_cube", "muito comum"], ["ghast", "comum"], ["strider", "na lava"]], "estruturas": ["fortaleza", "portal"], "img": "deltas-basalto.jpg"}
  ],
  estruturas: [
    {"id": "fortaleza", "nome": "Fortaleza do Nether", "icone": "nether_bricks", "apelido": "O castelo dos Blazes", "descricao": "Um castelo enorme de tijolos do Nether, com pontes altas por cima da lava, corredores e escadas. Pode aparecer em qualquer bioma do Nether e muitas vezes se estende por centenas de blocos.", "mobs": ["blaze", "wither_skeleton", "zombified_piglin", "magma_cube", "skeleton"], "destaques": [["spawner", "Até 2 geradores de Blaze, em plataformas com escadinhas"], ["nether_wart", "Fungo do Nether plantado nas salas com escadas: é a base de quase todas as poções"], ["wither_skeleton_skull", "O único lugar com Esqueletos Wither, que soltam o crânio para invocar o Wither"]], "dica": "Leve arco, escudo e comida. Os Esqueletos Wither aplicam Decomposição, que vai tirando a sua vida: um balde de leite cura.", "img": "fortaleza.jpg",
      "baus": [
        {"nome": "Baú da fortaleza", "descricao": "Fica nos corredores e nas pontes.", "itens": [
          ["gold_ingot", 1, 3, 46.5],
          ["saddle", 1, 1, 33.3],
          ["golden_horse_armor", 1, 1, 27.4],
          ["diamond", 1, 3, 17.9],
          ["iron_ingot", 1, 5, 17.9],
          ["golden_sword", 1, 1, 17.9],
          ["golden_chestplate", 1, 1, 17.9],
          ["flint_and_steel", 1, 1, 17.9],
          ["nether_wart", 3, 7, 17.9],
          ["copper_horse_armor", 1, 1, 17.9],
          ["iron_horse_armor", 1, 1, 17.9],
          ["diamond_horse_armor", 1, 1, 11.1],
          ["obsidian", 2, 4, 7.5],
          ["rib_armor_trim_smithing_template", 1, 1, 6.7]
        ]}
      ]},
    {"id": "bastiao", "nome": "Bastião em Ruínas", "icone": "gilded_blackstone", "apelido": "A casa dos Piglins", "descricao": "Um castelo de pedra-negra cheio de ouro e de Piglins. Aparece em todos os biomas do Nether, menos nos Deltas de basalto, e tem 4 tipos: pontes, estábulos de Hoglins, alojamentos e a sala do tesouro.", "mobs": ["piglin", "piglin_brute", "hoglin", "magma_cube"], "destaques": [["gold_block", "Blocos de ouro e pedra-negra dourada espalhados pelas paredes"], ["netherite_upgrade_smithing_template", "Único lugar com o Molde de Ferraria de Melhoria de Netherita (sempre na sala do tesouro)"], ["music_disc_pigstep", "Também é o único lugar com o disco Pigstep e o enfeite de armadura Focinho"], ["spawner", "A sala do tesouro tem geradores de Cubos de Magma"]], "dica": "Use pelo menos uma peça de ouro, mas cuidado: abrir baús e quebrar blocos de ouro deixa os Piglins bravos, e os Piglins Bárbaros atacam de qualquer jeito.", "img": "bastiao.jpg",
      "baus": [
        {"nome": "Sala do tesouro", "descricao": "O baú mais valioso do Nether: netherita, diamante e muito ouro.", "itens": [
          ["netherite_upgrade_smithing_template", 1, 1, 100.0],
          ["netherite_ingot", 1, 1, 35.0],
          ["spectral_arrow", 12, 25, 33.7],
          ["gold_block", 2, 5, 33.7],
          ["iron_block", 2, 5, 33.7],
          ["gold_ingot", 3, 9, 33.7],
          ["iron_ingot", 3, 9, 33.7],
          ["crying_obsidian", 3, 5, 33.7],
          ["quartz", 8, 23, 33.7],
          ["gilded_blackstone", 5, 15, 33.7],
          ["magma_cream", 3, 8, 33.7],
          ["ancient_debris", 1, 2, 32.3],
          ["diamond_sword", 1, 1, 28.1, 1],
          ["diamond_spear", 1, 1, 28.1, 1],
          ["diamond_chestplate", 1, 1, 26.1, 1],
          ["diamond_helmet", 1, 1, 26.1, 1],
          ["diamond_leggings", 1, 1, 26.1, 1],
          ["diamond_boots", 1, 1, 26.1, 1],
          ["netherite_scrap", 1, 1, 19.9],
          ["diamond", 2, 6, 12.8],
          ["snout_armor_trim_smithing_template", 1, 1, 8.3],
          ["enchanted_golden_apple", 1, 1, 5.3]
        ]},
        {"nome": "Ponte", "descricao": "Baú no tipo ponte; sempre traz uma magnetita.", "itens": [
          ["lodestone", 1, 1, 100.0],
          ["string", 1, 6, 47.9],
          ["leather", 1, 3, 47.9],
          ["arrow", 5, 17, 47.9],
          ["iron_nugget", 2, 6, 47.9],
          ["gold_nugget", 2, 6, 47.9],
          ["crossbow", 1, 1, 11.2, 1],
          ["spectral_arrow", 10, 28, 11.2],
          ["gilded_blackstone", 8, 12, 11.2],
          ["crying_obsidian", 3, 8, 11.2],
          ["gold_block", 1, 1, 11.2],
          ["gold_ingot", 4, 9, 11.2],
          ["iron_ingot", 4, 9, 11.2],
          ["golden_sword", 1, 1, 11.2],
          ["golden_chestplate", 1, 1, 11.2, 1],
          ["golden_helmet", 1, 1, 11.2, 1],
          ["golden_leggings", 1, 1, 11.2, 1],
          ["golden_boots", 1, 1, 11.2, 1],
          ["golden_axe", 1, 1, 11.2, 1],
          ["netherite_upgrade_smithing_template", 1, 1, 10.0],
          ["snout_armor_trim_smithing_template", 1, 1, 8.3]
        ]},
        {"nome": "Estábulo de Hoglins", "descricao": "Baús perto das baias dos Hoglins.", "itens": [
          ["golden_axe", 1, 1, 22.8, 1],
          ["crying_obsidian", 1, 5, 22.8],
          ["glowstone", 3, 6, 22.8],
          ["gilded_blackstone", 2, 5, 22.8],
          ["soul_sand", 2, 7, 22.8],
          ["crimson_nylium", 2, 7, 22.8],
          ["gold_nugget", 2, 8, 22.8],
          ["leather", 1, 3, 22.8],
          ["arrow", 5, 17, 22.8],
          ["string", 3, 8, 22.8],
          ["porkchop", 2, 5, 22.8],
          ["cooked_porkchop", 2, 5, 22.8],
          ["crimson_fungus", 2, 7, 22.8],
          ["crimson_roots", 2, 7, 22.8],
          ["ancient_debris", 1, 2, 16.4],
          ["gold_block", 2, 4, 16.0],
          ["diamond_shovel", 1, 1, 15.0, 1],
          ["diamond_pickaxe", 1, 1, 12.0, 1],
          ["saddle", 1, 1, 12.0],
          ["golden_carrot", 8, 17, 10.0],
          ["golden_apple", 1, 1, 10.0],
          ["netherite_upgrade_smithing_template", 1, 1, 10.0],
          ["snout_armor_trim_smithing_template", 1, 1, 8.3],
          ["netherite_scrap", 1, 1, 8.0]
        ]},
        {"nome": "Outros baús", "descricao": "Espalhados por todos os tipos de bastião.", "itens": [
          ["gilded_blackstone", 1, 5, 44.1],
          ["magma_cream", 2, 6, 44.1],
          ["arrow", 5, 17, 44.1],
          ["iron_chain", 2, 10, 24.4],
          ["bone_block", 3, 6, 24.4],
          ["iron_nugget", 2, 8, 24.4],
          ["obsidian", 4, 6, 24.4],
          ["gold_nugget", 2, 8, 24.4],
          ["string", 4, 6, 24.4],
          ["cooked_porkchop", 1, 1, 24.4],
          ["iron_sword", 1, 1, 19.0, 1],
          ["iron_block", 1, 1, 19.0],
          ["gold_block", 1, 1, 19.0],
          ["gold_ingot", 1, 6, 19.0],
          ["iron_ingot", 1, 6, 19.0],
          ["crying_obsidian", 1, 5, 19.0],
          ["golden_boots", 1, 1, 18.6, 1],
          ["crossbow", 1, 1, 15.8, 1],
          ["ancient_debris", 1, 1, 13.5],
          ["golden_carrot", 6, 17, 13.5],
          ["spectral_arrow", 10, 22, 11.2],
          ["enchanted_book", 1, 1, 11.2, 1],
          ["piglin_banner_pattern", 1, 1, 10.1],
          ["golden_apple", 1, 1, 10.1],
          ["netherite_upgrade_smithing_template", 1, 1, 10.0],
          ["golden_axe", 1, 1, 9.8, 1],
          ["golden_sword", 1, 1, 9.8],
          ["golden_chestplate", 1, 1, 9.8],
          ["golden_helmet", 1, 1, 9.8],
          ["golden_leggings", 1, 1, 9.8],
          ["snout_armor_trim_smithing_template", 1, 1, 8.3],
          ["diamond_pickaxe", 1, 1, 6.7, 1],
          ["diamond_shovel", 1, 1, 6.7],
          ["music_disc_pigstep", 1, 1, 5.6],
          ["netherite_scrap", 1, 1, 4.5]
        ]}
      ]},
    {"id": "fossil", "nome": "Fóssil do Nether", "icone": "bone_block", "apelido": "Esqueletos gigantes", "descricao": "Costelas e ossos gigantes feitos de 5 a 27 blocos de ossos, enterrados no chão do Vale de areia das almas. Não tem baú nem mobs próprios.", "mobs": [], "destaques": [["bone_block", "Blocos de ossos: viram 9 farinhas de osso cada"], ["dried_ghast", "1 em cada 3 fósseis tem um Ghast Seco do lado"]], "dica": "Coloque o Ghast Seco na água: com o tempo ele vira um filhote e depois um Ghast Feliz, que dá para montar e sair voando com até 4 pessoas!", "img": "fossil.jpg",
      "baus": []},
    {"id": "portal", "nome": "Portal em Ruínas", "icone": "crying_obsidian", "apelido": "Um portal quebrado", "descricao": "Um portal antigo e incompleto, de obsidiana e obsidiana chorona, cercado de netherrack e pedra-negra. Aparece em todos os biomas do Nether (e também no mundo normal). Às vezes é um portal gigante.", "mobs": [], "destaques": [["crying_obsidian", "Obsidiana chorona: serve para fazer uma âncora de renascimento"], ["chest", "Um baú com itens de ouro, que podem vir encantados"]], "dica": "Os itens de ouro do baú são ótimos para deixar os Piglins calmos. E se completar o portal com obsidiana, ele funciona de novo.", "img": "portal.jpg",
      "baus": [
        {"nome": "Baú do portal", "descricao": "Sempre tem um baú do lado do portal.", "itens": [
          ["lodestone", 1, 2, 66.7],
          ["obsidian", 1, 2, 46.4],
          ["flint", 1, 4, 46.4],
          ["iron_nugget", 9, 18, 46.4],
          ["flint_and_steel", 1, 1, 46.4],
          ["fire_charge", 1, 1, 46.4],
          ["golden_apple", 1, 1, 20.5],
          ["gold_nugget", 4, 24, 20.5],
          ["golden_sword", 1, 1, 20.5, 1],
          ["golden_axe", 1, 1, 20.5, 1],
          ["golden_hoe", 1, 1, 20.5, 1],
          ["golden_shovel", 1, 1, 20.5, 1],
          ["golden_pickaxe", 1, 1, 20.5, 1],
          ["golden_boots", 1, 1, 20.5, 1],
          ["golden_chestplate", 1, 1, 20.5, 1],
          ["golden_helmet", 1, 1, 20.5, 1],
          ["golden_leggings", 1, 1, 20.5, 1],
          ["glistering_melon_slice", 4, 12, 7.3],
          ["golden_horse_armor", 1, 1, 7.3],
          ["light_weighted_pressure_plate", 1, 1, 7.3],
          ["golden_carrot", 4, 12, 7.3],
          ["clock", 1, 1, 7.3],
          ["gold_ingot", 2, 8, 7.3],
          ["bell", 1, 1, 1.5],
          ["enchanted_golden_apple", 1, 1, 1.5],
          ["gold_block", 1, 2, 1.5]
        ]}
      ]}
  ],
  itens: {
    "ancient_debris": ["Detritos Ancestrais", "ancient_debris.png"],
    "arrow": ["Flecha", "arrow.png"],
    "basalt": ["Basalto", "basalt.png"],
    "bell": ["Sino", "bell.png"],
    "blackstone": ["Pedra-Negra", "blackstone.png"],
    "blaze_rod": ["Vara de Blaze", "blaze_rod.png"],
    "bone": ["Osso", "bone.png"],
    "bone_block": ["Bloco de Ossos", "bone_block.png"],
    "brown_mushroom": ["Cogumelo Marrom", "brown_mushroom.png"],
    "chest": ["Baú", "chest.png"],
    "clock": ["Relógio", "clock.png"],
    "coal": ["Carvão", "coal.png"],
    "cooked_porkchop": ["Costeleta de Porco Assada", "cooked_porkchop.png"],
    "copper_horse_armor": ["Armadura de Cobre para Cavalo", "copper_horse_armor.png"],
    "crimson_fungus": ["Fungo Carmesim", "crimson_fungus.png"],
    "crimson_nylium": ["Nicélio Carmesim", "crimson_nylium.png"],
    "crimson_roots": ["Raízes Carmesim", "crimson_roots.png"],
    "crimson_stem": ["Caule Carmesim", "crimson_stem.png"],
    "crossbow": ["Besta", "crossbow.png"],
    "crying_obsidian": ["Obsidiana Chorona", "crying_obsidian.png"],
    "diamond": ["Diamante", "diamond.png"],
    "diamond_boots": ["Botas de Diamante", "diamond_boots.png"],
    "diamond_chestplate": ["Peitoral de Diamante", "diamond_chestplate.png"],
    "diamond_helmet": ["Capacete de Diamante", "diamond_helmet.png"],
    "diamond_horse_armor": ["Armadura de Diamante para Cavalo", "diamond_horse_armor.png"],
    "diamond_leggings": ["Calças de Diamante", "diamond_leggings.png"],
    "diamond_pickaxe": ["Picareta de Diamante", "diamond_pickaxe.png"],
    "diamond_shovel": ["Pá de Diamante", "diamond_shovel.png"],
    "diamond_spear": ["Lança de Diamante", "diamond_spear.png"],
    "diamond_sword": ["Espada de Diamante", "diamond_sword.png"],
    "dried_ghast": ["Ghast Seco", "dried_ghast.png"],
    "enchanted_book": ["Livro Encantado", "enchanted_book.png"],
    "enchanted_golden_apple": ["Maçã Dourada Encantada", "enchanted_golden_apple.png"],
    "ender_pearl": ["Pérola de Ender", "ender_pearl.png"],
    "fire_charge": ["Bola de Fogo", "fire_charge.png"],
    "flint": ["Sílex", "flint.png"],
    "flint_and_steel": ["Pederneira", "flint_and_steel.png"],
    "ghast_tear": ["Lágrima de Ghast", "ghast_tear.png"],
    "gilded_blackstone": ["Pedra-Negra Dourada", "gilded_blackstone.png"],
    "glistering_melon_slice": ["Fatia de Melancia Reluzente", "glistering_melon_slice.png"],
    "glowstone": ["Pedra-Luminosa", "glowstone.png"],
    "gold_block": ["Bloco de Ouro", "gold_block.png"],
    "gold_ingot": ["Lingote de Ouro", "gold_ingot.png"],
    "gold_nugget": ["Pepita de Ouro", "gold_nugget.png"],
    "golden_apple": ["Maçã Dourada", "golden_apple.png"],
    "golden_axe": ["Machado de Ouro", "golden_axe.png"],
    "golden_boots": ["Botas de Ouro", "golden_boots.png"],
    "golden_carrot": ["Cenoura Dourada", "golden_carrot.png"],
    "golden_chestplate": ["Peitoral de Ouro", "golden_chestplate.png"],
    "golden_helmet": ["Capacete de Ouro", "golden_helmet.png"],
    "golden_hoe": ["Enxada de Ouro", "golden_hoe.png"],
    "golden_horse_armor": ["Armadura de Ouro para Cavalo", "golden_horse_armor.png"],
    "golden_leggings": ["Calças de Ouro", "golden_leggings.png"],
    "golden_pickaxe": ["Picareta de Ouro", "golden_pickaxe.png"],
    "golden_shovel": ["Pá de Ouro", "golden_shovel.png"],
    "golden_sword": ["Espada de Ouro", "golden_sword.png"],
    "gravel": ["Cascalho", "gravel.png"],
    "gunpowder": ["Pólvora", "gunpowder.png"],
    "iron_block": ["Bloco de Ferro", "iron_block.png"],
    "iron_chain": ["Corrente de Ferro", "iron_chain.png"],
    "iron_horse_armor": ["Armadura de Ferro para Cavalo", "iron_horse_armor.png"],
    "iron_ingot": ["Lingote de Ferro", "iron_ingot.png"],
    "iron_nugget": ["Pepita de Ferro", "iron_nugget.png"],
    "iron_sword": ["Espada de Ferro", "iron_sword.png"],
    "leather": ["Couro", "leather.png"],
    "light_weighted_pressure_plate": ["Placa de Pressão de Pesagem Leve", "light_weighted_pressure_plate.png"],
    "lodestone": ["Magnetita", "lodestone.png"],
    "magma_block": ["Bloco de Magma", "magma_block.png"],
    "magma_cream": ["Creme de Magma", "magma_cream.png"],
    "music_disc_pigstep": ["Disco Musical (Pigstep)", "music_disc_pigstep.png"],
    "nether_bricks": ["Tijolos do Nether", "nether_bricks.png"],
    "nether_gold_ore": ["Minério de Ouro do Nether", "nether_gold_ore.png"],
    "nether_quartz_ore": ["Minério de Quartzo do Nether", "nether_quartz_ore.png"],
    "nether_sprouts": ["Brotos do Nether", "nether_sprouts.png"],
    "nether_wart": ["Fungo do Nether", "nether_wart.png"],
    "nether_wart_block": ["Bloco de Fungos do Nether", "nether_wart_block.png"],
    "netherite_ingot": ["Lingote de Netherita", "netherite_ingot.png"],
    "netherite_scrap": ["Fragmentos de Netherita", "netherite_scrap.png"],
    "netherite_upgrade_smithing_template": ["Molde de Ferraria (Melhoria de Netherita)", "netherite_upgrade_smithing_template.png"],
    "netherrack": ["Netherrack", "netherrack.png"],
    "obsidian": ["Obsidiana", "obsidian.png"],
    "piglin_banner_pattern": ["Figura para Estandarte de Focinho", "piglin_banner_pattern.png"],
    "porkchop": ["Costeleta de Porco Crua", "porkchop.png"],
    "quartz": ["Quartzo do Nether", "quartz.png"],
    "red_mushroom": ["Cogumelo Vermelho", "red_mushroom.png"],
    "rib_armor_trim_smithing_template": ["Molde de Ferraria (Enfeite de Costelas)", "rib_armor_trim_smithing_template.png"],
    "rotten_flesh": ["Carne Podre", "rotten_flesh.png"],
    "saddle": ["Sela", "saddle.png"],
    "shroomlight": ["Cogubrilho", "shroomlight.png"],
    "snout_armor_trim_smithing_template": ["Molde de Ferraria (Enfeite de Focinho)", "snout_armor_trim_smithing_template.png"],
    "soul_sand": ["Areia das Almas", "soul_sand.png"],
    "soul_soil": ["Terra das Almas", "soul_soil.png"],
    "spawner": ["Gerador de Criaturas", "spawner.png"],
    "spectral_arrow": ["Flecha Espectral", "spectral_arrow.png"],
    "string": ["Linha", "string.png"],
    "twisting_vines": ["Trepadeiras-Retorcidas", "twisting_vines.png"],
    "warped_fungus": ["Fungo Distorcido", "warped_fungus.png"],
    "warped_nylium": ["Nicélio Distorcido", "warped_nylium.png"],
    "warped_roots": ["Raízes Distorcidas", "warped_roots.png"],
    "warped_stem": ["Caule Distorcido", "warped_stem.png"],
    "warped_wart_block": ["Bloco de Fungos Distorcidos", "warped_wart_block.png"],
    "weeping_vines": ["Trepadeiras-Choronas", "weeping_vines.png"],
    "wither_skeleton_skull": ["Crânio de Esqueleto Wither", "wither_skeleton_skull.png"]
  }
};
