/* =============================================================
   Dados do guia As Poções
   -------------------------------------------------------------
   Todas as poções que dá para fazer no suporte de poções, com a
   receita (base + ingrediente), a duração de cada versão e o que
   cada uma faz. Java Edition 26.3.

   base: "estranha" (Poção Estranha), "agua" (Frasco de Água) ou o id
         de outra poção, quando ela é feita a partir dela.
   segundos: [normal, com redstone, com pedra-luminosa]; null quando a
         versão não existe ou o efeito é instantâneo.
   ============================================================= */
window.MINEGUIA_POCOES = {
  grupos: [{"id": "beber", "nome": "Para você beber", "desc": "Efeitos que ajudam você"}, {"id": "atacar", "nome": "Para jogar nos inimigos", "desc": "Efeitos ruins: use a versão arremessável"}, {"id": "especial", "nome": "Efeitos especiais", "desc": "Agem quando o mob se machuca ou morre"}],
  pocoes: [
    {"id": "cura", "grupo": "beber", "nome": "Poção de Cura", "efeitoNome": "Vida Instantânea", "ingrediente": "glistering_melon_slice", "base": "estranha", "segundos": [null, null, null], "forte": "II", "efeito": "Recupera 2 corações na hora (4 corações na versão II). Em mortos-vivos, como zumbis e esqueletos, ela machuca em vez de curar.", "dica": "A versão arremessável é a cura mais rápida no meio de uma luta: jogue no chão, aos seus pés."},
    {"id": "regeneracao", "grupo": "beber", "nome": "Poção de Regeneração", "efeitoNome": "Regeneração", "ingrediente": "ghast_tear", "base": "estranha", "segundos": [45, 90, 22.5], "forte": "II", "efeito": "Recupera a vida aos poucos: meio coração a cada 2,5 segundos (duas vezes mais rápido na versão II).", "dica": "A Lágrima de Ghast é rara: mate os Ghasts longe da lava, senão ela cai e some."},
    {"id": "forca", "grupo": "beber", "nome": "Poção de Força", "efeitoNome": "Força", "ingrediente": "blaze_powder", "base": "estranha", "segundos": [180, 480, 90], "forte": "II", "efeito": "Seus golpes corpo a corpo causam +1,5 coração de dano (+3 corações na versão II).", "dica": "Com uma espada com Afiação, quase tudo cai em poucos golpes. Ótima contra o Ender Dragon."},
    {"id": "agilidade", "grupo": "beber", "nome": "Poção de Agilidade", "efeitoNome": "Velocidade", "ingrediente": "sugar", "base": "estranha", "segundos": [180, 480, 90], "forte": "II", "efeito": "Você anda e corre 20% mais rápido (40% na versão II).", "dica": "O açúcar sai da cana-de-açúcar, que cresce fácil perto da água."},
    {"id": "salto", "grupo": "beber", "nome": "Poção de Salto", "efeitoNome": "Supersalto", "ingrediente": "rabbit_foot", "base": "estranha", "segundos": [180, 480, 90], "forte": "II", "efeito": "Você pula mais alto (quase 2 blocos, ou 2,5 na versão II) e leva menos dano de queda.", "dica": "O Pé de Coelho é um drop raro dos coelhos: Pilhagem na espada ajuda."},
    {"id": "resistencia-fogo", "grupo": "beber", "nome": "Poção de Resistência ao Fogo", "efeitoNome": "Resistência ao Fogo", "ingrediente": "magma_cream", "base": "estranha", "segundos": [180, 480, null], "forte": null, "efeito": "Deixa você imune a fogo e lava. Dá até para nadar na lava (mas sem enxergar quase nada).", "dica": "Leve sempre para o Nether. O Creme de Magma vem dos Cubos de Magma ou de bola de slime + pó de blaze."},
    {"id": "respiracao-aquatica", "grupo": "beber", "nome": "Poção de Respiração Aquática", "efeitoNome": "Respiração Aquática", "ingrediente": "pufferfish", "base": "estranha", "segundos": [180, 480, null], "forte": null, "efeito": "Você respira debaixo d'água sem perder o ar.", "dica": "Perfeita para explorar ruínas oceânicas e o Monumento Oceânico. O baiacu se pesca ou se pega com balde."},
    {"id": "visao-noturna", "grupo": "beber", "nome": "Poção de Visão Noturna", "efeitoNome": "Visão Noturna", "ingrediente": "golden_carrot", "base": "estranha", "segundos": [180, 480, null], "forte": null, "efeito": "Deixa tudo claro como de dia, até nas cavernas mais escuras e debaixo d'água.", "dica": "Ótima para minerar sem gastar tochas e para nadar no fundo do mar. Junte com Respiração Aquática."},
    {"id": "invisibilidade", "grupo": "beber", "nome": "Poção de Invisibilidade", "efeitoNome": "Invisibilidade", "ingrediente": "fermented_spider_eye", "base": "visao-noturna", "segundos": [180, 480, null], "forte": null, "efeito": "Você fica invisível: os mobs só percebem você bem de perto. A armadura e o item na mão continuam aparecendo.", "dica": "Tire a armadura para ficar invisível de verdade. Os mobs ainda escutam e percebem você quando chegam perto."},
    {"id": "queda-lenta", "grupo": "beber", "nome": "Poção de Queda Lenta", "efeitoNome": "Queda Lenta", "ingrediente": "phantom_membrane", "base": "estranha", "segundos": [90, 240, null], "forte": null, "efeito": "Você cai devagar, como uma pena, e não leva dano de queda.", "dica": "A Membrana de Espectro vem dos Espectros, que aparecem quando você passa 3 noites sem dormir. Salva vidas no End."},
    {"id": "mestre-tartaruga", "grupo": "beber", "nome": "Poção do Mestre-Tartaruga", "efeitoNome": "Lentidão + Resistência", "ingrediente": "turtle_helmet", "base": "estranha", "segundos": [20, 40, 20], "forte": "II", "efeito": "Você fica quase parado (Lentidão IV), mas leva 60% menos dano (80% na versão II).", "dica": "O Casco de Tartaruga é feito com 5 escamas que os filhotes de tartaruga soltam ao crescer."},
    {"id": "veneno", "grupo": "atacar", "nome": "Poção de Veneno", "efeitoNome": "Veneno", "ingrediente": "spider_eye", "base": "estranha", "segundos": [45, 90, 21.6], "forte": "II", "efeito": "Tira vida aos poucos, mas nunca mata: o veneno para quando sobra meio coração.", "dica": "Aranhas e mortos-vivos (zumbis, esqueletos...) não são afetados pelo veneno."},
    {"id": "dano", "grupo": "atacar", "nome": "Poção de Dano", "efeitoNome": "Dano Instantâneo", "ingrediente": "fermented_spider_eye", "base": "cura", "segundos": [null, null, null], "forte": "II", "efeito": "Causa 3 corações de dano na hora (6 corações na versão II). Em mortos-vivos, ela cura em vez de machucar.", "dica": "Também sai de Poção de Veneno + Olho de Aranha Fermentado. Contra zumbis e esqueletos, use a de Cura."},
    {"id": "lentidao", "grupo": "atacar", "nome": "Poção de Lentidão", "efeitoNome": "Lentidão", "ingrediente": "fermented_spider_eye", "base": "agilidade", "segundos": [90, 240, 20], "forte": "IV", "efeito": "Deixa o alvo 15% mais lento (60% na versão IV).", "dica": "Também sai de Poção de Salto + Olho de Aranha Fermentado. Ótima para fugir ou segurar um inimigo perto."},
    {"id": "fraqueza", "grupo": "atacar", "nome": "Poção de Fraqueza", "efeitoNome": "Fraqueza", "ingrediente": "fermented_spider_eye", "base": "agua", "segundos": [90, 240, null], "forte": null, "efeito": "Os golpes corpo a corpo do alvo causam 2 corações a menos.", "dica": "É a única poção que não precisa de Fungo do Nether. Jogue uma arremessável num Aldeão Zumbi e dê uma maçã dourada: ele vira aldeão de novo."},
    {"id": "ventania", "grupo": "especial", "nome": "Poção de Ventania", "efeitoNome": "Ventania", "ingrediente": "breeze_rod", "base": "estranha", "segundos": [180, null, null], "forte": null, "efeito": "Quando o mob afetado morre, ele solta uma rajada de vento que empurra tudo em volta.", "dica": "A Vara de Vórtice vem dos Vórtices das Câmaras do Desafio."},
    {"id": "tecitura", "grupo": "especial", "nome": "Poção de Tecitura", "efeitoNome": "Tecitura", "ingrediente": "cobweb", "base": "estranha", "segundos": [180, null, null], "forte": null, "efeito": "As teias atrapalham menos quem está com o efeito, e quando ele morre deixa 2 ou 3 teias de aranha no chão.", "dica": "Arremesse num grupo de inimigos: cada um que morrer vira uma armadilha de teia."},
    {"id": "pegajosa", "grupo": "especial", "nome": "Poção Pegajosa", "efeitoNome": "Pegajoso", "ingrediente": "slime_block", "base": "estranha", "segundos": [180, null, null], "forte": null, "efeito": "Quando o mob afetado morre, nascem dois slimes médios no lugar.", "dica": "Um jeito de conseguir bolas de slime sem achar um pântano ou um chunk de slime."},
    {"id": "infestacao", "grupo": "especial", "nome": "Poção de Infestação", "efeitoNome": "Infestação", "ingrediente": "stone", "base": "estranha", "segundos": [180, null, null], "forte": null, "efeito": "Toda vez que o mob afetado leva dano, tem 10% de chance de soltar traças.", "dica": "O ingrediente é a pedra comum, a mais fácil de conseguir de todas."}
  ],
  itens: {
    "base:agua": ["Frasco de Água", "potion_water.png"],
    "base:estranha": ["Poção Estranha", "potion_awkward.png"],
    "base:comum": ["Poção Comum", "potion_mundane.png"],
    "base:espessa": ["Poção Espessa", "potion_thick.png"],
    "splash:agua": ["Frasco de Água Arremessável", "splash_potion_water.png"],
    "potion:cura": ["Poção de Cura", "potion_healing.png"],
    "splash_potion:cura": ["Poção Arremessável de Cura", "splash_potion_healing.png"],
    "lingering_potion:cura": ["Poção Prolongada de Cura", "lingering_potion_healing.png"],
    "tipped_arrow:cura": ["Flecha de Cura", "tipped_arrow_healing.png"],
    "potion:regeneracao": ["Poção de Regeneração", "potion_regeneration.png"],
    "splash_potion:regeneracao": ["Poção Arremessável de Regeneração", "splash_potion_regeneration.png"],
    "lingering_potion:regeneracao": ["Poção Prolongada de Regeneração", "lingering_potion_regeneration.png"],
    "tipped_arrow:regeneracao": ["Flecha de Regeneração", "tipped_arrow_regeneration.png"],
    "potion:forca": ["Poção de Força", "potion_strength.png"],
    "splash_potion:forca": ["Poção Arremessável de Força", "splash_potion_strength.png"],
    "lingering_potion:forca": ["Poção Prolongada de Força", "lingering_potion_strength.png"],
    "tipped_arrow:forca": ["Flecha de Força", "tipped_arrow_strength.png"],
    "potion:agilidade": ["Poção de Agilidade", "potion_swiftness.png"],
    "splash_potion:agilidade": ["Poção Arremessável de Agilidade", "splash_potion_swiftness.png"],
    "lingering_potion:agilidade": ["Poção Prolongada de Agilidade", "lingering_potion_swiftness.png"],
    "tipped_arrow:agilidade": ["Flecha de Agilidade", "tipped_arrow_swiftness.png"],
    "potion:salto": ["Poção de Salto", "potion_leaping.png"],
    "splash_potion:salto": ["Poção Arremessável de Salto", "splash_potion_leaping.png"],
    "lingering_potion:salto": ["Poção Prolongada de Salto", "lingering_potion_leaping.png"],
    "tipped_arrow:salto": ["Flecha de Salto", "tipped_arrow_leaping.png"],
    "potion:resistencia-fogo": ["Poção de Resistência ao Fogo", "potion_fire_resistance.png"],
    "splash_potion:resistencia-fogo": ["Poção Arremessável de Resistência ao Fogo", "splash_potion_fire_resistance.png"],
    "lingering_potion:resistencia-fogo": ["Poção Prolongada de Resistência ao Fogo", "lingering_potion_fire_resistance.png"],
    "tipped_arrow:resistencia-fogo": ["Flecha de Resistência ao Fogo", "tipped_arrow_fire_resistance.png"],
    "potion:respiracao-aquatica": ["Poção de Respiração Aquática", "potion_water_breathing.png"],
    "splash_potion:respiracao-aquatica": ["Poção Arremessável de Respiração Aquática", "splash_potion_water_breathing.png"],
    "lingering_potion:respiracao-aquatica": ["Poção Prolongada de Respiração Aquática", "lingering_potion_water_breathing.png"],
    "tipped_arrow:respiracao-aquatica": ["Flecha de Respiração Aquática", "tipped_arrow_water_breathing.png"],
    "potion:visao-noturna": ["Poção de Visão Noturna", "potion_night_vision.png"],
    "splash_potion:visao-noturna": ["Poção Arremessável de Visão Noturna", "splash_potion_night_vision.png"],
    "lingering_potion:visao-noturna": ["Poção Prolongada de Visão Noturna", "lingering_potion_night_vision.png"],
    "tipped_arrow:visao-noturna": ["Flecha de Visão Noturna", "tipped_arrow_night_vision.png"],
    "potion:invisibilidade": ["Poção de Invisibilidade", "potion_invisibility.png"],
    "splash_potion:invisibilidade": ["Poção Arremessável de Invisibilidade", "splash_potion_invisibility.png"],
    "lingering_potion:invisibilidade": ["Poção Prolongada de Invisibilidade", "lingering_potion_invisibility.png"],
    "tipped_arrow:invisibilidade": ["Flecha de Invisibilidade", "tipped_arrow_invisibility.png"],
    "potion:queda-lenta": ["Poção de Queda Lenta", "potion_slow_falling.png"],
    "splash_potion:queda-lenta": ["Poção Arremessável de Queda Lenta", "splash_potion_slow_falling.png"],
    "lingering_potion:queda-lenta": ["Poção Prolongada de Queda Lenta", "lingering_potion_slow_falling.png"],
    "tipped_arrow:queda-lenta": ["Flecha de Queda Lenta", "tipped_arrow_slow_falling.png"],
    "potion:mestre-tartaruga": ["Poção do Mestre-Tartaruga", "potion_turtle_master.png"],
    "splash_potion:mestre-tartaruga": ["Poção Arremessável do Mestre-Tartaruga", "splash_potion_turtle_master.png"],
    "lingering_potion:mestre-tartaruga": ["Poção Prolongada do Mestre-Tartaruga", "lingering_potion_turtle_master.png"],
    "tipped_arrow:mestre-tartaruga": ["Flecha do Mestre-Tartaruga", "tipped_arrow_turtle_master.png"],
    "potion:veneno": ["Poção de Veneno", "potion_poison.png"],
    "splash_potion:veneno": ["Poção Arremessável de Veneno", "splash_potion_poison.png"],
    "lingering_potion:veneno": ["Poção Prolongada de Veneno", "lingering_potion_poison.png"],
    "tipped_arrow:veneno": ["Flecha de Veneno", "tipped_arrow_poison.png"],
    "potion:dano": ["Poção de Dano", "potion_harming.png"],
    "splash_potion:dano": ["Poção Arremessável de Dano", "splash_potion_harming.png"],
    "lingering_potion:dano": ["Poção Prolongada de Dano", "lingering_potion_harming.png"],
    "tipped_arrow:dano": ["Flecha de Dano", "tipped_arrow_harming.png"],
    "potion:lentidao": ["Poção de Lentidão", "potion_slowness.png"],
    "splash_potion:lentidao": ["Poção Arremessável de Lentidão", "splash_potion_slowness.png"],
    "lingering_potion:lentidao": ["Poção Prolongada de Lentidão", "lingering_potion_slowness.png"],
    "tipped_arrow:lentidao": ["Flecha de Lentidão", "tipped_arrow_slowness.png"],
    "potion:fraqueza": ["Poção de Fraqueza", "potion_weakness.png"],
    "splash_potion:fraqueza": ["Poção Arremessável de Fraqueza", "splash_potion_weakness.png"],
    "lingering_potion:fraqueza": ["Poção Prolongada de Fraqueza", "lingering_potion_weakness.png"],
    "tipped_arrow:fraqueza": ["Flecha de Fraqueza", "tipped_arrow_weakness.png"],
    "potion:ventania": ["Poção de Ventania", "potion_wind_charged.png"],
    "splash_potion:ventania": ["Poção Arremessável de Ventania", "splash_potion_wind_charged.png"],
    "lingering_potion:ventania": ["Poção Prolongada de Ventania", "lingering_potion_wind_charged.png"],
    "tipped_arrow:ventania": ["Flecha de Ventania", "tipped_arrow_wind_charged.png"],
    "potion:tecitura": ["Poção de Tecitura", "potion_weaving.png"],
    "splash_potion:tecitura": ["Poção Arremessável de Tecitura", "splash_potion_weaving.png"],
    "lingering_potion:tecitura": ["Poção Prolongada de Tecitura", "lingering_potion_weaving.png"],
    "tipped_arrow:tecitura": ["Flecha de Tecitura", "tipped_arrow_weaving.png"],
    "potion:pegajosa": ["Poção Pegajosa", "potion_oozing.png"],
    "splash_potion:pegajosa": ["Poção Arremessável Pegajosa", "splash_potion_oozing.png"],
    "lingering_potion:pegajosa": ["Poção Prolongada Pegajosa", "lingering_potion_oozing.png"],
    "tipped_arrow:pegajosa": ["Flecha Pegajosa", "tipped_arrow_oozing.png"],
    "potion:infestacao": ["Poção de Infestação", "potion_infested.png"],
    "splash_potion:infestacao": ["Poção Arremessável de Infestação", "splash_potion_infested.png"],
    "lingering_potion:infestacao": ["Poção Prolongada de Infestação", "lingering_potion_infested.png"],
    "tipped_arrow:infestacao": ["Flecha de Infestação", "tipped_arrow_infested.png"],
    "arrow": ["Flecha", "arrow.png"],
    "blaze_powder": ["Pó de Blaze", "blaze_powder.png"],
    "blaze_rod": ["Vara de Blaze", "blaze_rod.png"],
    "breeze_rod": ["Vara de Vórtice", "breeze_rod.png"],
    "brewing_stand": ["Suporte de Poções", "brewing_stand.png"],
    "carrot": ["Cenoura", "carrot.png"],
    "cauldron": ["Caldeirão", "cauldron.png"],
    "cobblestone": ["Pedregulho", "cobblestone.png"],
    "cobweb": ["Teia de Aranha", "cobweb.png"],
    "dragon_breath": ["Bafo do Dragão", "dragon_breath.png"],
    "fermented_spider_eye": ["Olho de Aranha Fermentado", "fermented_spider_eye.png"],
    "ghast_tear": ["Lágrima de Ghast", "ghast_tear.png"],
    "glass": ["Vidro", "glass.png"],
    "glass_bottle": ["Frasco de Vidro", "glass_bottle.png"],
    "glistering_melon_slice": ["Fatia de Melancia Reluzente", "glistering_melon_slice.png"],
    "glowstone_dust": ["Pó de Pedra-Luminosa", "glowstone_dust.png"],
    "gold_nugget": ["Pepita de Ouro", "gold_nugget.png"],
    "golden_carrot": ["Cenoura Dourada", "golden_carrot.png"],
    "gunpowder": ["Pólvora", "gunpowder.png"],
    "magma_cream": ["Creme de Magma", "magma_cream.png"],
    "melon_slice": ["Fatia de Melancia", "melon_slice.png"],
    "nether_wart": ["Fungo do Nether", "nether_wart.png"],
    "phantom_membrane": ["Membrana de Espectro", "phantom_membrane.png"],
    "pufferfish": ["Baiacu", "pufferfish.png"],
    "rabbit_foot": ["Pé de Coelho", "rabbit_foot.png"],
    "redstone": ["Pó de Redstone", "redstone.png"],
    "slime_ball": ["Bola de Slime", "slime_ball.png"],
    "slime_block": ["Bloco de Slime", "slime_block.png"],
    "spider_eye": ["Olho de Aranha", "spider_eye.png"],
    "stone": ["Pedra", "stone.png"],
    "sugar": ["Açúcar", "sugar.png"],
    "sugar_cane": ["Cana-de-Açúcar", "sugar_cane.png"],
    "turtle_helmet": ["Casco de Tartaruga", "turtle_helmet.png"],
    "turtle_scute": ["Escama de Tartaruga", "turtle_scute.png"],
    "water_bucket": ["Balde de Água", "water_bucket.png"]
  }
};
